INSERT INTO code_lists.describing_line_type VALUES (1, 1, 'Viiva');
INSERT INTO code_lists.describing_line_type VALUES (2, 2, 'Katkoviiva');
INSERT INTO code_lists.describing_line_type VALUES (3, 3, 'Paksu viiva');
INSERT INTO code_lists.describing_line_type VALUES (4, 4, 'Paksu katkoviiva');
INSERT INTO code_lists.describing_line_type VALUES (5, 5, 'Johtoalueen viiva');

INSERT INTO code_lists.finnish_area_type VALUES (1, 1, 'Maankäyttöalue');
INSERT INTO code_lists.finnish_area_type VALUES (2, 2, 'Kaavan osa-alue');
INSERT INTO code_lists.finnish_area_type VALUES (3, 3, 'Kaavan tarkennemerkintä');

INSERT INTO code_lists.finnish_document_role VALUES (1, 1, 'Liiteaineisto');
INSERT INTO code_lists.finnish_document_role VALUES (2, 2, 'Kaavaselostus');
INSERT INTO code_lists.finnish_document_role VALUES (3, 3, 'Lisätieto');
INSERT INTO code_lists.finnish_document_role VALUES (4, 4, 'Päätös');

INSERT INTO code_lists.finnish_document_type VALUES (1, 1, 'Kaavaselostus', NULL);
INSERT INTO code_lists.finnish_document_type VALUES (2, 2, 'Lausunto', '07');
INSERT INTO code_lists.finnish_document_type VALUES (3, 3, 'Mielipide', '08');
INSERT INTO code_lists.finnish_document_type VALUES (4, 4, 'Muistutus', '10');
INSERT INTO code_lists.finnish_document_type VALUES (5, 5, 'Vastine', '20');
INSERT INTO code_lists.finnish_document_type VALUES (6, 6, 'Päätös', '12');
INSERT INTO code_lists.finnish_document_type VALUES (7, 7, 'Havainnekuva', '02');
INSERT INTO code_lists.finnish_document_type VALUES (8, 8, 'Vaikutustenarviointi', NULL);
INSERT INTO code_lists.finnish_document_type VALUES (9, 9, 'Kaavakartta', '03');
INSERT INTO code_lists.finnish_document_type VALUES (10, 10, 'Osallistumis- ja arviointisuunnitelma', '11');
INSERT INTO code_lists.finnish_document_type VALUES (11, 11, 'Hakemus', '01');
INSERT INTO code_lists.finnish_document_type VALUES (12, 12, 'Karttaliite', '04');
INSERT INTO code_lists.finnish_document_type VALUES (13, 13, 'Kirje', '05');
INSERT INTO code_lists.finnish_document_type VALUES (14, 14, 'Kuulutus', '06');
INSERT INTO code_lists.finnish_document_type VALUES (15, 15, 'Muistio', '09');
INSERT INTO code_lists.finnish_document_type VALUES (16, 16, 'Pöytäkirja', '13');
INSERT INTO code_lists.finnish_document_type VALUES (17, 17, 'Raportti', '14');
INSERT INTO code_lists.finnish_document_type VALUES (18, 18, 'Selvitys', '15');
INSERT INTO code_lists.finnish_document_type VALUES (19, 19, 'Sopimus', '16');
INSERT INTO code_lists.finnish_document_type VALUES (20, 20, 'Suunnitelma', '17');
INSERT INTO code_lists.finnish_document_type VALUES (21, 21, 'Suunnitteluohje', '18');
INSERT INTO code_lists.finnish_document_type VALUES (22, 22, 'Valitus', '19');
INSERT INTO code_lists.finnish_document_type VALUES (23, 23, 'Muu asiakirja', '21');

INSERT INTO code_lists.finnish_informative_feature_type VALUES (1, 1, 'Kiinteistöt');
INSERT INTO code_lists.finnish_informative_feature_type VALUES (2, 2, 'Maaperä');
INSERT INTO code_lists.finnish_informative_feature_type VALUES (3, 3, 'Maasto');
INSERT INTO code_lists.finnish_informative_feature_type VALUES (4, 4, 'Luonto');
INSERT INTO code_lists.finnish_informative_feature_type VALUES (5, 5, 'Kulttuuriympäristö');
INSERT INTO code_lists.finnish_informative_feature_type VALUES (6, 6, 'Ympäristöterveys');
INSERT INTO code_lists.finnish_informative_feature_type VALUES (7, 7, 'Liikenne');
INSERT INTO code_lists.finnish_informative_feature_type VALUES (8, 8, 'Yhdyskuntarakenne');
INSERT INTO code_lists.finnish_informative_feature_type VALUES (9, 9, 'Energiahuolto');
INSERT INTO code_lists.finnish_informative_feature_type VALUES (10, 10, 'Kunnallistekniset verkostot');
INSERT INTO code_lists.finnish_informative_feature_type VALUES (11, 11, 'Rakennukset');
INSERT INTO code_lists.finnish_informative_feature_type VALUES (12, 12, 'Muu');

INSERT INTO code_lists.finnish_land_use_kind VALUES (12, 'C0', 'Keskustatoiminnot', 'Keskustatoiminnot', 'C', '0102');
INSERT INTO code_lists.finnish_land_use_kind VALUES (13, 'C1', 'Keskustatoiminnot', 'Keskustatoimintojen alue', 'C', '010201');
INSERT INTO code_lists.finnish_land_use_kind VALUES (14, 'C2', 'Keskustatoiminnot', 'Keskustatoimintojen alakeskus', 'C', '010202');
INSERT INTO code_lists.finnish_land_use_kind VALUES (15, 'C3', 'Keskustatoiminnot', 'Muut keskustatoiminnot', 'C', '010203');
INSERT INTO code_lists.finnish_land_use_kind VALUES (16, 'K0', 'Liike- ja toimistorakentaminen', 'Liike- ja toimistorakentaminen', 'K', '0103');
INSERT INTO code_lists.finnish_land_use_kind VALUES (17, 'K1', 'Liike- ja toimistorakentaminen', 'Liikerakennusten alue', 'KL', '101301');
INSERT INTO code_lists.finnish_land_use_kind VALUES (18, 'K2', 'Liike- ja toimistorakentaminen', 'Liikerakennusten korttelialue, jolle saa sijoittaa vähittäiskaupan suuryksikön', 'KM', '010304');
INSERT INTO code_lists.finnish_land_use_kind VALUES (19, 'K5', 'Liike- ja toimistorakentaminen', 'Kaupallisten palveluiden alue', 'KM', '010304');
INSERT INTO code_lists.finnish_land_use_kind VALUES (20, 'K3', 'Liike- ja toimistorakentaminen', 'Toimistorakennusten alue', 'KT', '101302');
INSERT INTO code_lists.finnish_land_use_kind VALUES (21, 'K4', 'Liike- ja toimistorakentaminen', 'Toimitilarakennusten alue', 'KTY', '101303');
INSERT INTO code_lists.finnish_land_use_kind VALUES (22, 'K6', 'Liike- ja toimistorakentaminen', 'Muu liike- ja toimistorakentaminen', 'K', '101305');
INSERT INTO code_lists.finnish_land_use_kind VALUES (23, 'P0', 'Palvelut', 'Palvelut', 'P', '0104');
INSERT INTO code_lists.finnish_land_use_kind VALUES (24, 'P10', 'Palvelut', 'Palvelurakennusten  alue', 'P', '10401');
INSERT INTO code_lists.finnish_land_use_kind VALUES (25, 'P1', 'Palvelut', 'Lähipalveluiden alue', 'PL', '10402');
INSERT INTO code_lists.finnish_land_use_kind VALUES (26, 'P2', 'Palvelut', 'Huvi- ja viihdepalveluiden alue', 'PV', '10403');
INSERT INTO code_lists.finnish_land_use_kind VALUES (27, 'P11', 'Palvelut', 'Muut palvelut', 'P', '10404');
INSERT INTO code_lists.finnish_land_use_kind VALUES (28, 'Y', 'Julkiset palvelut', 'Julkiset palvelut', 'Y', '0105');
INSERT INTO code_lists.finnish_land_use_kind VALUES (29, 'Y1', 'Julkiset palvelut', 'Julkiset palvelut', 'Y', '010501');
INSERT INTO code_lists.finnish_land_use_kind VALUES (30, 'P3', 'Julkiset palvelut', 'Yleisten rakennusten alue', 'Y', '010502');
INSERT INTO code_lists.finnish_land_use_kind VALUES (31, 'P4', 'Julkiset palvelut', 'Julkisten lähipalveluiden alue', 'YL', '010503');
INSERT INTO code_lists.finnish_land_use_kind VALUES (32, 'P5', 'Julkiset palvelut', 'Hallinto- ja virastorakennusten alue', 'YH', '010504');
INSERT INTO code_lists.finnish_land_use_kind VALUES (33, 'P6', 'Julkiset palvelut', 'Opetustoimintaa palvelevien rakennusten alue', 'YO', '010505');
INSERT INTO code_lists.finnish_land_use_kind VALUES (34, 'P7', 'Julkiset palvelut', 'Sosiaalitointa ja terveydenhuoltoa palvelevien rakennusten alue', 'YS', '010506');
INSERT INTO code_lists.finnish_land_use_kind VALUES (35, 'Y10', 'Julkiset palvelut', 'Kulttuuritoimintaa palvelevien rakennusten alue', 'YY', '010507');
INSERT INTO code_lists.finnish_land_use_kind VALUES (36, 'Y11', 'Julkiset palvelut', 'Museorakennusten alue', 'YM', '010508');
INSERT INTO code_lists.finnish_land_use_kind VALUES (37, 'P8', 'Julkiset palvelut', 'Kirkkojen ja muiden seurakunnallisten rakennusten alue', 'YK', '010509');
INSERT INTO code_lists.finnish_land_use_kind VALUES (38, 'P9', 'Julkiset palvelut', 'Urheilutoimintaa palvelevien rakennusten alue', 'YU', '010510');
INSERT INTO code_lists.finnish_land_use_kind VALUES (39, 'Y12', 'Julkiset palvelut', 'Julkisten palveluiden ja hallinnon alue', 'Y', '010511');
INSERT INTO code_lists.finnish_land_use_kind VALUES (40, 'Y13', 'Julkiset palvelut', 'Muut julkiset palvelut', 'Y', '010512');
INSERT INTO code_lists.finnish_land_use_kind VALUES (41, 'T0', 'Työ- ja tuotanto', 'Työ- ja tuotanto', 'T', '0106');
INSERT INTO code_lists.finnish_land_use_kind VALUES (42, 'T2', 'Työ- ja tuotanto', 'Työpaikka-alue', 'T', '010601');
INSERT INTO code_lists.finnish_land_use_kind VALUES (43, 'T3', 'Työ- ja tuotanto', 'Teollisuusalue', 'TT', '010602');
INSERT INTO code_lists.finnish_land_use_kind VALUES (44, 'T4', 'Työ- ja tuotanto', 'Varastorakennusten alue', 'TV', '010603');
INSERT INTO code_lists.finnish_land_use_kind VALUES (45, 'T5', 'Työ- ja tuotanto', 'Alue, jolle saa sijoittaa merkittävän, vaarallisia kemikaaleja valmistavan tai varastoivan laitoksen', 'T/kem', '010604');
INSERT INTO code_lists.finnish_land_use_kind VALUES (46, 'T6', 'Työ- ja tuotanto', 'Ympäristövaikutuksiltaan merkittävien teollisuustoimintojen alue', 'TT', '010605');
INSERT INTO code_lists.finnish_land_use_kind VALUES (47, 'T7', 'Työ- ja tuotanto', 'Kiertotalous', 'T', '010606');
INSERT INTO code_lists.finnish_land_use_kind VALUES (48, 'T1', 'Työ- ja tuotanto', 'Teollisuusalue, jolla ympäristö asettaa toiminnan laadulle erityisiä vaatimuksia', 'TY', '010607');
INSERT INTO code_lists.finnish_land_use_kind VALUES (49, 'T8', 'Työ- ja tuotanto', 'Muu työpaikka- ja tuotantoalue', 'T', '010608');
INSERT INTO code_lists.finnish_land_use_kind VALUES (50, 'V', 'Virkistys', 'Virkistys', 'V', '0107');
INSERT INTO code_lists.finnish_land_use_kind VALUES (51, 'V0', 'Virkistys', 'Virkistysalue', 'V', '010701');
INSERT INTO code_lists.finnish_land_use_kind VALUES (52, 'V1', 'Virkistys', 'Puisto', 'VP', '010702');
INSERT INTO code_lists.finnish_land_use_kind VALUES (53, 'V2', 'Virkistys', 'Lähivirkistysalue', 'VL', '010703');
INSERT INTO code_lists.finnish_land_use_kind VALUES (54, 'V3', 'Virkistys', 'Leikkipuisto', 'VK', '010704');
INSERT INTO code_lists.finnish_land_use_kind VALUES (55, 'V4', 'Virkistys', 'Urheilu- ja virkistyspalvelujen alue', 'VU', '010705');
INSERT INTO code_lists.finnish_land_use_kind VALUES (56, 'V5', 'Virkistys', 'Retkeily- ja ulkoilualue', 'VR', '010706');
INSERT INTO code_lists.finnish_land_use_kind VALUES (57, 'V6', 'Virkistys', 'Uimaranta-alue', 'VV', '010707');
INSERT INTO code_lists.finnish_land_use_kind VALUES (58, 'V7', 'Virkistys', 'Lähimetsä', 'V', '010708');
INSERT INTO code_lists.finnish_land_use_kind VALUES (59, 'V8', 'Virkistys', 'Muu virkistysalue', 'V', '010709');
INSERT INTO code_lists.finnish_land_use_kind VALUES (60, 'R0', 'Loma-asuminen ja matkailu', 'Loma-asuminen ja matkailu', 'R', '0108');
INSERT INTO code_lists.finnish_land_use_kind VALUES (61, 'R1', 'Loma-asuminen ja matkailu', 'Loma-asuntojen alue', 'RA', '010801');
INSERT INTO code_lists.finnish_land_use_kind VALUES (62, 'R2', 'Loma-asuminen ja matkailu', 'Matkailua palvelevien rakennusten alue', 'RM', '010802');
INSERT INTO code_lists.finnish_land_use_kind VALUES (63, 'R3', 'Loma-asuminen ja matkailu', 'Leirintäalue', 'RL', '010803');
INSERT INTO code_lists.finnish_land_use_kind VALUES (64, 'R5', 'Loma-asuminen ja matkailu', 'Asuntovaunualue', 'RV', '010804');
INSERT INTO code_lists.finnish_land_use_kind VALUES (65, 'R4', 'Loma-asuminen ja matkailu', 'Siirtolapuutarha-/palstaviljelyalue', 'RP', '010805');
INSERT INTO code_lists.finnish_land_use_kind VALUES (67, 'L', 'Liikenne', 'Liikenne', 'L', '0109');
INSERT INTO code_lists.finnish_land_use_kind VALUES (68, 'L0', 'Liikenne', 'Liikennealue', 'L', '010901');
INSERT INTO code_lists.finnish_land_use_kind VALUES (69, 'L2', 'Liikenne', 'Yleisen tien alue', 'LT', '010902');
INSERT INTO code_lists.finnish_land_use_kind VALUES (70, 'L3', 'Liikenne', 'Rautatieliikenteen alue', 'LR', '010903');
INSERT INTO code_lists.finnish_land_use_kind VALUES (71, 'L4', 'Liikenne', 'Lentoliikenteen alue', 'LL', '010904');
INSERT INTO code_lists.finnish_land_use_kind VALUES (72, 'L5', 'Liikenne', 'Satama-alue', 'LS', '010905');
INSERT INTO code_lists.finnish_land_use_kind VALUES (73, 'L6', 'Liikenne', 'Kanava-alue', 'LK', '010906');
INSERT INTO code_lists.finnish_land_use_kind VALUES (74, 'L7', 'Liikenne', 'Venesatama/venevalkama', 'LV', '010907');
INSERT INTO code_lists.finnish_land_use_kind VALUES (76, 'L10', 'Liikenne', 'Huoltoasema-alue', 'LH', '010909');
INSERT INTO code_lists.finnish_land_use_kind VALUES (78, 'L12', 'Liikenne', 'Tavaraliikenteen terminaalialue', 'LTA', '010911');
INSERT INTO code_lists.finnish_land_use_kind VALUES (80, 'L9', 'Liikenne', 'Autopaikkojen alue', 'LPA', '010913');
INSERT INTO code_lists.finnish_land_use_kind VALUES (81, 'L1', 'Liikenne', 'Katu', 'KATU', '010914');
INSERT INTO code_lists.finnish_land_use_kind VALUES (82, 'L13', 'Liikenne', 'Katuaukio/tori', 'TORI', '010914');
INSERT INTO code_lists.finnish_land_use_kind VALUES (83, 'L14', 'Liikenne', 'Jalankululle tai pyöräilylle varattu katu', 'KATU', '010914');
INSERT INTO code_lists.finnish_land_use_kind VALUES (84, 'L15', 'Liikenne', 'Muu liikennealue', 'L', '010915');
INSERT INTO code_lists.finnish_land_use_kind VALUES (85, 'E', 'Erityisalueet', 'Erityisalueet', 'E', '0110');
INSERT INTO code_lists.finnish_land_use_kind VALUES (86, 'E0', 'Erityisalueet', 'Erityisalue', 'E', '011001');
INSERT INTO code_lists.finnish_land_use_kind VALUES (87, 'E1', 'Erityisalueet', 'Yhdyskuntateknisen huollon alue', 'ET', '011002');
INSERT INTO code_lists.finnish_land_use_kind VALUES (88, 'E2', 'Erityisalueet', 'Energiahuollon alue', 'EN', '011003');
INSERT INTO code_lists.finnish_land_use_kind VALUES (89, 'E3', 'Erityisalueet', 'Jätteenkäsittelyalue', 'EJ', '011004');
INSERT INTO code_lists.finnish_land_use_kind VALUES (90, 'E4', 'Erityisalueet', 'Maa-ainesten ottoalue', 'EO', '011005');
INSERT INTO code_lists.finnish_land_use_kind VALUES (11, 'A10', 'Asuminen', 'Muu asuminen', 'A', '010109');
INSERT INTO code_lists.finnish_land_use_kind VALUES (79, 'L16', 'Liikenne', 'Yleisten pysäköintilaitosten alue', 'LPY', '010912');
INSERT INTO code_lists.finnish_land_use_kind VALUES (77, 'L11', 'Liikenne', 'Henkilöliikenteen terminaalialue', 'LHA', '010910');
INSERT INTO code_lists.finnish_land_use_kind VALUES (66, 'R6', 'Loma-asuminen ja matkailu', 'Muu loma-asumisen tai matkailun laue', 'R', '010806');
INSERT INTO code_lists.finnish_land_use_kind VALUES (75, 'L8', 'Liikenne', 'Yleinen pysäköintialue', 'LP', '010908');
INSERT INTO code_lists.finnish_land_use_kind VALUES (91, 'E6', 'Erityisalueet', 'Kaivosalue', 'EK', '011006');
INSERT INTO code_lists.finnish_land_use_kind VALUES (92, 'E7', 'Erityisalueet', 'Mastoalue', 'EMT', '011007');
INSERT INTO code_lists.finnish_land_use_kind VALUES (93, 'E8', 'Erityisalueet', 'Ampumarata-alue', 'EA', '011008');
INSERT INTO code_lists.finnish_land_use_kind VALUES (94, 'E9', 'Erityisalueet', 'Puolustusvoimien alue', 'EP', '011009');
INSERT INTO code_lists.finnish_land_use_kind VALUES (95, 'E10', 'Erityisalueet', 'Hautausmaa-alue', 'EH', '011010');
INSERT INTO code_lists.finnish_land_use_kind VALUES (96, 'E5', 'Erityisalueet', 'Suojaviheralue', 'EV', '011011');
INSERT INTO code_lists.finnish_land_use_kind VALUES (97, 'E11', 'Erityisalueet', 'Tuulivoimaloiden alue', 'EN', '011012');
INSERT INTO code_lists.finnish_land_use_kind VALUES (98, 'E12', 'Erityisalueet', 'Moottorirata', 'EM', '011013');
INSERT INTO code_lists.finnish_land_use_kind VALUES (99, 'E13', 'Erityisalueet', 'Maa-ainesten vastaanotto- ja läjitysalue', 'E', '011014');
INSERT INTO code_lists.finnish_land_use_kind VALUES (100, 'E14', 'Erityisalueet', 'Vankila-alue', 'E', '011015');
INSERT INTO code_lists.finnish_land_use_kind VALUES (101, 'E15', 'Erityisalueet', 'Muu erityisalue', NULL, '011016');
INSERT INTO code_lists.finnish_land_use_kind VALUES (102, 'S', 'Suojelu', 'Suojelu', 'S', '0111');
INSERT INTO code_lists.finnish_land_use_kind VALUES (103, 'S0', 'Suojelu', 'Suojelualue', 'S', '011101');
INSERT INTO code_lists.finnish_land_use_kind VALUES (104, 'S1', 'Suojelu', 'Luonnonsuojelualue', 'SL', '011102');
INSERT INTO code_lists.finnish_land_use_kind VALUES (105, 'S2', 'Suojelu', 'Muinaismuistoalue', 'SM', '011103');
INSERT INTO code_lists.finnish_land_use_kind VALUES (107, 'S4', 'Suojelu', 'Rakennussuojelulain nojalla suojeltu alue', 'SR', '011105');
INSERT INTO code_lists.finnish_land_use_kind VALUES (108, 'S5', 'Suojelu', 'Muu suojelualue', 'S', '011106');
INSERT INTO code_lists.finnish_land_use_kind VALUES (109, 'M', 'Maa- ja metsätalous', 'Maa- ja metsätalous', 'M', '0112');
INSERT INTO code_lists.finnish_land_use_kind VALUES (110, 'M0', 'Maa- ja metsätalous', 'Maa- ja metsätalousalue', 'M', '011201');
INSERT INTO code_lists.finnish_land_use_kind VALUES (111, 'M1', 'Maa- ja metsätalous', 'Maatalousalue', 'MT', '011202');
INSERT INTO code_lists.finnish_land_use_kind VALUES (113, 'M3', 'Maa- ja metsätalous', 'Puutarha- ja kasvihuonealue', 'MP', '011204');
INSERT INTO code_lists.finnish_land_use_kind VALUES (114, 'M4', 'Maa- ja metsätalous', 'Maisemallisesti arvokas peltoalue', 'MA', '011205');
INSERT INTO code_lists.finnish_land_use_kind VALUES (115, 'M5', 'Maa- ja metsätalous', 'Poronhoitovaltainen maa- ja metsätalousalue', 'M', '011206');
INSERT INTO code_lists.finnish_land_use_kind VALUES (116, 'M6', 'Maa- ja metsätalous', 'Muu maa- ja metsätalosualue', 'M', '011207');
INSERT INTO code_lists.finnish_land_use_kind VALUES (117, 'W', 'Vesialueet', 'Vesialueet', 'W', '0113');
INSERT INTO code_lists.finnish_land_use_kind VALUES (118, 'W0', 'Vesialueet', 'Vesialue', 'W', '011301');
INSERT INTO code_lists.finnish_land_use_kind VALUES (119, 'W1', 'Vesialueet', 'Muu vesialue', 'W', '011302');
INSERT INTO code_lists.finnish_land_use_kind VALUES (9, 'A8', 'Asuminen', 'Kyläalue', 'AT', '010107');
INSERT INTO code_lists.finnish_land_use_kind VALUES (8, 'A5', 'Asuminen', 'Asuin-, liike- ja toimistorakennusten alue', 'AL', '010101');
INSERT INTO code_lists.finnish_land_use_kind VALUES (10, 'A9', 'Asuminen', 'Erityisryhmien palveluasuminen', 'A', '010108');
INSERT INTO code_lists.finnish_land_use_kind VALUES (1, 'A0', 'Asuminen', 'Asuminen', 'A', '0101');
INSERT INTO code_lists.finnish_land_use_kind VALUES (3, 'A2', 'Asuminen', 'Asuinpientaloalue', 'AP', '010102');
INSERT INTO code_lists.finnish_land_use_kind VALUES (2, 'A1', 'Asuminen', 'Asuinkerrostaloalue', 'AK', '010101');
INSERT INTO code_lists.finnish_land_use_kind VALUES (5, 'A4', 'Asuminen', 'Erillispientaloalue', 'AO', '010104');
INSERT INTO code_lists.finnish_land_use_kind VALUES (4, 'A3', 'Asuminen', 'Rivitalojen ja muiden kytkettyjen asuinrakennusten alue', 'AR', '010103');
INSERT INTO code_lists.finnish_land_use_kind VALUES (7, 'A6', 'Asuminen', 'Maatilan talouskeskuksen alue', 'AM', '010106');
INSERT INTO code_lists.finnish_land_use_kind VALUES (6, 'A7', 'Asuminen', 'Asumista palveleva yhteiskäyttöinen alue', 'A/yk', '010105');
INSERT INTO code_lists.finnish_land_use_kind VALUES (106, 'S3', 'Suojelu', 'Rakennuslainsäädännön nojalla suojeltava alue', 'SR', '011104');
INSERT INTO code_lists.finnish_land_use_kind VALUES (112, 'M2', 'Maa- ja metsätalous', 'Kotieläintalouden suuryksikön alue', 'ME', '011203');
INSERT INTO code_lists.finnish_land_use_kind VALUES (120, 'M7', 'Maa- ja metsätalous', 'Maa- ja metsätalousalue, jolla on erityistä ulkoilun ohjaamistarvetta', 'MU', '011201');
INSERT INTO code_lists.finnish_land_use_kind VALUES (121, 'M8', 'Maa- ja metsätalous', 'Maa- ja metsätalousalue, jolla on erityisiä ympäristöarvoja', 'MY', '011201');

INSERT INTO code_lists.finnish_language VALUES (1, 1, 'Suomi');
INSERT INTO code_lists.finnish_language VALUES (2, 2, 'Ruotsi');
INSERT INTO code_lists.finnish_language VALUES (3, 3, 'Suomi ja ruotsi');

INSERT INTO code_lists.finnish_municipality_codes VALUES (1, '020', 'Akaa');
INSERT INTO code_lists.finnish_municipality_codes VALUES (2, '005', 'Alajärvi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (3, '009', 'Alavieska');
INSERT INTO code_lists.finnish_municipality_codes VALUES (4, '010', 'Alavus');
INSERT INTO code_lists.finnish_municipality_codes VALUES (5, '016', 'Asikkala');
INSERT INTO code_lists.finnish_municipality_codes VALUES (6, '018', 'Askola');
INSERT INTO code_lists.finnish_municipality_codes VALUES (7, '019', 'Aura');
INSERT INTO code_lists.finnish_municipality_codes VALUES (8, '035', 'Brändö');
INSERT INTO code_lists.finnish_municipality_codes VALUES (9, '043', 'Eckerö');
INSERT INTO code_lists.finnish_municipality_codes VALUES (10, '046', 'Enonkoski');
INSERT INTO code_lists.finnish_municipality_codes VALUES (11, '047', 'Enontekiö');
INSERT INTO code_lists.finnish_municipality_codes VALUES (12, '049', 'Espoo');
INSERT INTO code_lists.finnish_municipality_codes VALUES (13, '050', 'Eura');
INSERT INTO code_lists.finnish_municipality_codes VALUES (14, '051', 'Eurajoki');
INSERT INTO code_lists.finnish_municipality_codes VALUES (15, '052', 'Evijärvi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (16, '060', 'Finström');
INSERT INTO code_lists.finnish_municipality_codes VALUES (17, '061', 'Forssa');
INSERT INTO code_lists.finnish_municipality_codes VALUES (18, '062', 'Föglö');
INSERT INTO code_lists.finnish_municipality_codes VALUES (19, '065', 'Geta');
INSERT INTO code_lists.finnish_municipality_codes VALUES (20, '069', 'Haapajärvi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (21, '071', 'Haapavesi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (22, '072', 'Hailuoto');
INSERT INTO code_lists.finnish_municipality_codes VALUES (23, '074', 'Halsua');
INSERT INTO code_lists.finnish_municipality_codes VALUES (24, '075', 'Hamina');
INSERT INTO code_lists.finnish_municipality_codes VALUES (25, '076', 'Hammarland');
INSERT INTO code_lists.finnish_municipality_codes VALUES (26, '077', 'Hankasalmi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (27, '078', 'Hanko');
INSERT INTO code_lists.finnish_municipality_codes VALUES (28, '079', 'Harjavalta');
INSERT INTO code_lists.finnish_municipality_codes VALUES (29, '081', 'Hartola');
INSERT INTO code_lists.finnish_municipality_codes VALUES (30, '082', 'Hattula');
INSERT INTO code_lists.finnish_municipality_codes VALUES (31, '086', 'Hausjärvi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (32, '111', 'Heinola');
INSERT INTO code_lists.finnish_municipality_codes VALUES (33, '090', 'Heinävesi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (34, '091', 'Helsinki');
INSERT INTO code_lists.finnish_municipality_codes VALUES (35, '097', 'Hirvensalmi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (36, '098', 'Hollola');
INSERT INTO code_lists.finnish_municipality_codes VALUES (37, '099', 'Honkajoki');
INSERT INTO code_lists.finnish_municipality_codes VALUES (38, '102', 'Huittinen');
INSERT INTO code_lists.finnish_municipality_codes VALUES (39, '103', 'Humppila');
INSERT INTO code_lists.finnish_municipality_codes VALUES (40, '105', 'Hyrynsalmi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (41, '106', 'Hyvinkää');
INSERT INTO code_lists.finnish_municipality_codes VALUES (42, '108', 'Hämeenkyrö');
INSERT INTO code_lists.finnish_municipality_codes VALUES (43, '109', 'Hämeenlinna');
INSERT INTO code_lists.finnish_municipality_codes VALUES (44, '139', 'Ii');
INSERT INTO code_lists.finnish_municipality_codes VALUES (45, '140', 'Iisalmi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (46, '142', 'Iitti');
INSERT INTO code_lists.finnish_municipality_codes VALUES (47, '143', 'Ikaalinen');
INSERT INTO code_lists.finnish_municipality_codes VALUES (48, '145', 'Ilmajoki');
INSERT INTO code_lists.finnish_municipality_codes VALUES (49, '146', 'Ilomantsi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (50, '153', 'Imatra');
INSERT INTO code_lists.finnish_municipality_codes VALUES (51, '148', 'Inari');
INSERT INTO code_lists.finnish_municipality_codes VALUES (52, '149', 'Inkoo');
INSERT INTO code_lists.finnish_municipality_codes VALUES (53, '151', 'Isojoki');
INSERT INTO code_lists.finnish_municipality_codes VALUES (54, '152', 'Isokyrö');
INSERT INTO code_lists.finnish_municipality_codes VALUES (55, '165', 'Janakkala');
INSERT INTO code_lists.finnish_municipality_codes VALUES (56, '167', 'Joensuu');
INSERT INTO code_lists.finnish_municipality_codes VALUES (57, '169', 'Jokioinen');
INSERT INTO code_lists.finnish_municipality_codes VALUES (58, '170', 'Jomala');
INSERT INTO code_lists.finnish_municipality_codes VALUES (59, '171', 'Joroinen');
INSERT INTO code_lists.finnish_municipality_codes VALUES (60, '172', 'Joutsa');
INSERT INTO code_lists.finnish_municipality_codes VALUES (61, '176', 'Juuka');
INSERT INTO code_lists.finnish_municipality_codes VALUES (62, '177', 'Juupajoki');
INSERT INTO code_lists.finnish_municipality_codes VALUES (63, '178', 'Juva');
INSERT INTO code_lists.finnish_municipality_codes VALUES (64, '179', 'Jyväskylä');
INSERT INTO code_lists.finnish_municipality_codes VALUES (65, '181', 'Jämijärvi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (66, '182', 'Jämsä');
INSERT INTO code_lists.finnish_municipality_codes VALUES (67, '186', 'Järvenpää');
INSERT INTO code_lists.finnish_municipality_codes VALUES (68, '202', 'Kaarina');
INSERT INTO code_lists.finnish_municipality_codes VALUES (69, '204', 'Kaavi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (70, '205', 'Kajaani');
INSERT INTO code_lists.finnish_municipality_codes VALUES (71, '208', 'Kalajoki');
INSERT INTO code_lists.finnish_municipality_codes VALUES (72, '211', 'Kangasala');
INSERT INTO code_lists.finnish_municipality_codes VALUES (73, '213', 'Kangasniemi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (74, '214', 'Kankaanpää');
INSERT INTO code_lists.finnish_municipality_codes VALUES (75, '216', 'Kannonkoski');
INSERT INTO code_lists.finnish_municipality_codes VALUES (76, '217', 'Kannus');
INSERT INTO code_lists.finnish_municipality_codes VALUES (77, '218', 'Karijoki');
INSERT INTO code_lists.finnish_municipality_codes VALUES (78, '224', 'Karkkila');
INSERT INTO code_lists.finnish_municipality_codes VALUES (79, '226', 'Karstula');
INSERT INTO code_lists.finnish_municipality_codes VALUES (80, '230', 'Karvia');
INSERT INTO code_lists.finnish_municipality_codes VALUES (81, '231', 'Kaskinen');
INSERT INTO code_lists.finnish_municipality_codes VALUES (82, '232', 'Kauhajoki');
INSERT INTO code_lists.finnish_municipality_codes VALUES (83, '233', 'Kauhava');
INSERT INTO code_lists.finnish_municipality_codes VALUES (84, '235', 'Kauniainen');
INSERT INTO code_lists.finnish_municipality_codes VALUES (85, '236', 'Kaustinen');
INSERT INTO code_lists.finnish_municipality_codes VALUES (86, '239', 'Keitele');
INSERT INTO code_lists.finnish_municipality_codes VALUES (87, '240', 'Kemi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (88, '320', 'Kemijärvi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (89, '241', 'Keminmaa');
INSERT INTO code_lists.finnish_municipality_codes VALUES (90, '322', 'Kemiönsaari');
INSERT INTO code_lists.finnish_municipality_codes VALUES (91, '244', 'Kempele');
INSERT INTO code_lists.finnish_municipality_codes VALUES (92, '245', 'Kerava');
INSERT INTO code_lists.finnish_municipality_codes VALUES (93, '249', 'Keuruu');
INSERT INTO code_lists.finnish_municipality_codes VALUES (94, '250', 'Kihniö');
INSERT INTO code_lists.finnish_municipality_codes VALUES (95, '256', 'Kinnula');
INSERT INTO code_lists.finnish_municipality_codes VALUES (96, '257', 'Kirkkonummi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (97, '260', 'Kitee');
INSERT INTO code_lists.finnish_municipality_codes VALUES (98, '261', 'Kittilä');
INSERT INTO code_lists.finnish_municipality_codes VALUES (99, '263', 'Kiuruvesi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (100, '265', 'Kivijärvi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (101, '271', 'Kokemäki');
INSERT INTO code_lists.finnish_municipality_codes VALUES (102, '272', 'Kokkola');
INSERT INTO code_lists.finnish_municipality_codes VALUES (103, '273', 'Kolari');
INSERT INTO code_lists.finnish_municipality_codes VALUES (104, '275', 'Konnevesi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (105, '276', 'Kontiolahti');
INSERT INTO code_lists.finnish_municipality_codes VALUES (106, '280', 'Korsnäs');
INSERT INTO code_lists.finnish_municipality_codes VALUES (107, '284', 'Koski Tl');
INSERT INTO code_lists.finnish_municipality_codes VALUES (108, '285', 'Kotka');
INSERT INTO code_lists.finnish_municipality_codes VALUES (109, '286', 'Kouvola');
INSERT INTO code_lists.finnish_municipality_codes VALUES (110, '287', 'Kristiinankaupunki');
INSERT INTO code_lists.finnish_municipality_codes VALUES (111, '288', 'Kruunupyy');
INSERT INTO code_lists.finnish_municipality_codes VALUES (112, '290', 'Kuhmo');
INSERT INTO code_lists.finnish_municipality_codes VALUES (113, '291', 'Kuhmoinen');
INSERT INTO code_lists.finnish_municipality_codes VALUES (114, '295', 'Kumlinge');
INSERT INTO code_lists.finnish_municipality_codes VALUES (115, '297', 'Kuopio');
INSERT INTO code_lists.finnish_municipality_codes VALUES (116, '300', 'Kuortane');
INSERT INTO code_lists.finnish_municipality_codes VALUES (117, '301', 'Kurikka');
INSERT INTO code_lists.finnish_municipality_codes VALUES (118, '304', 'Kustavi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (119, '305', 'Kuusamo');
INSERT INTO code_lists.finnish_municipality_codes VALUES (120, '312', 'Kyyjärvi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (121, '316', 'Kärkölä');
INSERT INTO code_lists.finnish_municipality_codes VALUES (122, '317', 'Kärsämäki');
INSERT INTO code_lists.finnish_municipality_codes VALUES (123, '318', 'Kökar');
INSERT INTO code_lists.finnish_municipality_codes VALUES (124, '398', 'Lahti');
INSERT INTO code_lists.finnish_municipality_codes VALUES (125, '399', 'Laihia');
INSERT INTO code_lists.finnish_municipality_codes VALUES (126, '400', 'Laitila');
INSERT INTO code_lists.finnish_municipality_codes VALUES (127, '407', 'Lapinjärvi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (128, '402', 'Lapinlahti');
INSERT INTO code_lists.finnish_municipality_codes VALUES (129, '403', 'Lappajärvi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (130, '405', 'Lappeenranta');
INSERT INTO code_lists.finnish_municipality_codes VALUES (131, '408', 'Lapua');
INSERT INTO code_lists.finnish_municipality_codes VALUES (132, '410', 'Laukaa');
INSERT INTO code_lists.finnish_municipality_codes VALUES (133, '416', 'Lemi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (134, '417', 'Lemland');
INSERT INTO code_lists.finnish_municipality_codes VALUES (135, '418', 'Lempäälä');
INSERT INTO code_lists.finnish_municipality_codes VALUES (136, '420', 'Leppävirta');
INSERT INTO code_lists.finnish_municipality_codes VALUES (137, '421', 'Lestijärvi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (138, '422', 'Lieksa');
INSERT INTO code_lists.finnish_municipality_codes VALUES (139, '423', 'Lieto');
INSERT INTO code_lists.finnish_municipality_codes VALUES (140, '425', 'Liminka');
INSERT INTO code_lists.finnish_municipality_codes VALUES (141, '426', 'Liperi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (142, '444', 'Lohja');
INSERT INTO code_lists.finnish_municipality_codes VALUES (143, '430', 'Loimaa');
INSERT INTO code_lists.finnish_municipality_codes VALUES (144, '433', 'Loppi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (145, '434', 'Loviisa');
INSERT INTO code_lists.finnish_municipality_codes VALUES (146, '435', 'Luhanka');
INSERT INTO code_lists.finnish_municipality_codes VALUES (147, '436', 'Lumijoki');
INSERT INTO code_lists.finnish_municipality_codes VALUES (148, '438', 'Lumparland');
INSERT INTO code_lists.finnish_municipality_codes VALUES (149, '440', 'Luoto');
INSERT INTO code_lists.finnish_municipality_codes VALUES (150, '441', 'Luumäki');
INSERT INTO code_lists.finnish_municipality_codes VALUES (151, '475', 'Maalahti');
INSERT INTO code_lists.finnish_municipality_codes VALUES (152, '478', 'Maarianhamina - Mariehamn');
INSERT INTO code_lists.finnish_municipality_codes VALUES (153, '480', 'Marttila');
INSERT INTO code_lists.finnish_municipality_codes VALUES (154, '481', 'Masku');
INSERT INTO code_lists.finnish_municipality_codes VALUES (155, '483', 'Merijärvi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (156, '484', 'Merikarvia');
INSERT INTO code_lists.finnish_municipality_codes VALUES (157, '489', 'Miehikkälä');
INSERT INTO code_lists.finnish_municipality_codes VALUES (158, '491', 'Mikkeli');
INSERT INTO code_lists.finnish_municipality_codes VALUES (159, '494', 'Muhos');
INSERT INTO code_lists.finnish_municipality_codes VALUES (160, '495', 'Multia');
INSERT INTO code_lists.finnish_municipality_codes VALUES (161, '498', 'Muonio');
INSERT INTO code_lists.finnish_municipality_codes VALUES (162, '499', 'Mustasaari');
INSERT INTO code_lists.finnish_municipality_codes VALUES (163, '500', 'Muurame');
INSERT INTO code_lists.finnish_municipality_codes VALUES (164, '503', 'Mynämäki');
INSERT INTO code_lists.finnish_municipality_codes VALUES (165, '504', 'Myrskylä');
INSERT INTO code_lists.finnish_municipality_codes VALUES (166, '505', 'Mäntsälä');
INSERT INTO code_lists.finnish_municipality_codes VALUES (167, '508', 'Mänttä-Vilppula');
INSERT INTO code_lists.finnish_municipality_codes VALUES (168, '507', 'Mäntyharju');
INSERT INTO code_lists.finnish_municipality_codes VALUES (169, '529', 'Naantali');
INSERT INTO code_lists.finnish_municipality_codes VALUES (170, '531', 'Nakkila');
INSERT INTO code_lists.finnish_municipality_codes VALUES (171, '535', 'Nivala');
INSERT INTO code_lists.finnish_municipality_codes VALUES (172, '536', 'Nokia');
INSERT INTO code_lists.finnish_municipality_codes VALUES (173, '538', 'Nousiainen');
INSERT INTO code_lists.finnish_municipality_codes VALUES (174, '541', 'Nurmes');
INSERT INTO code_lists.finnish_municipality_codes VALUES (175, '543', 'Nurmijärvi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (176, '545', 'Närpiö');
INSERT INTO code_lists.finnish_municipality_codes VALUES (177, '560', 'Orimattila');
INSERT INTO code_lists.finnish_municipality_codes VALUES (178, '561', 'Oripää');
INSERT INTO code_lists.finnish_municipality_codes VALUES (179, '562', 'Orivesi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (180, '563', 'Oulainen');
INSERT INTO code_lists.finnish_municipality_codes VALUES (181, '564', 'Oulu');
INSERT INTO code_lists.finnish_municipality_codes VALUES (182, '309', 'Outokumpu');
INSERT INTO code_lists.finnish_municipality_codes VALUES (183, '576', 'Padasjoki');
INSERT INTO code_lists.finnish_municipality_codes VALUES (184, '577', 'Paimio');
INSERT INTO code_lists.finnish_municipality_codes VALUES (185, '578', 'Paltamo');
INSERT INTO code_lists.finnish_municipality_codes VALUES (186, '445', 'Parainen');
INSERT INTO code_lists.finnish_municipality_codes VALUES (187, '580', 'Parikkala');
INSERT INTO code_lists.finnish_municipality_codes VALUES (188, '581', 'Parkano');
INSERT INTO code_lists.finnish_municipality_codes VALUES (189, '599', 'Pedersören kunta');
INSERT INTO code_lists.finnish_municipality_codes VALUES (190, '583', 'Pelkosenniemi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (191, '854', 'Pello');
INSERT INTO code_lists.finnish_municipality_codes VALUES (192, '584', 'Perho');
INSERT INTO code_lists.finnish_municipality_codes VALUES (193, '588', 'Pertunmaa');
INSERT INTO code_lists.finnish_municipality_codes VALUES (194, '592', 'Petäjävesi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (195, '593', 'Pieksämäki');
INSERT INTO code_lists.finnish_municipality_codes VALUES (196, '595', 'Pielavesi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (197, '598', 'Pietarsaari');
INSERT INTO code_lists.finnish_municipality_codes VALUES (198, '601', 'Pihtipudas');
INSERT INTO code_lists.finnish_municipality_codes VALUES (199, '604', 'Pirkkala');
INSERT INTO code_lists.finnish_municipality_codes VALUES (200, '607', 'Polvijärvi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (201, '608', 'Pomarkku');
INSERT INTO code_lists.finnish_municipality_codes VALUES (202, '609', 'Pori');
INSERT INTO code_lists.finnish_municipality_codes VALUES (203, '611', 'Pornainen');
INSERT INTO code_lists.finnish_municipality_codes VALUES (204, '638', 'Porvoo');
INSERT INTO code_lists.finnish_municipality_codes VALUES (205, '614', 'Posio');
INSERT INTO code_lists.finnish_municipality_codes VALUES (206, '615', 'Pudasjärvi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (207, '616', 'Pukkila');
INSERT INTO code_lists.finnish_municipality_codes VALUES (208, '619', 'Punkalaidun');
INSERT INTO code_lists.finnish_municipality_codes VALUES (209, '620', 'Puolanka');
INSERT INTO code_lists.finnish_municipality_codes VALUES (210, '623', 'Puumala');
INSERT INTO code_lists.finnish_municipality_codes VALUES (211, '624', 'Pyhtää');
INSERT INTO code_lists.finnish_municipality_codes VALUES (212, '625', 'Pyhäjoki');
INSERT INTO code_lists.finnish_municipality_codes VALUES (213, '626', 'Pyhäjärvi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (214, '630', 'Pyhäntä');
INSERT INTO code_lists.finnish_municipality_codes VALUES (215, '631', 'Pyhäranta');
INSERT INTO code_lists.finnish_municipality_codes VALUES (216, '635', 'Pälkäne');
INSERT INTO code_lists.finnish_municipality_codes VALUES (217, '636', 'Pöytyä');
INSERT INTO code_lists.finnish_municipality_codes VALUES (218, '678', 'Raahe');
INSERT INTO code_lists.finnish_municipality_codes VALUES (219, '710', 'Raasepori');
INSERT INTO code_lists.finnish_municipality_codes VALUES (220, '680', 'Raisio');
INSERT INTO code_lists.finnish_municipality_codes VALUES (221, '681', 'Rantasalmi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (222, '683', 'Ranua');
INSERT INTO code_lists.finnish_municipality_codes VALUES (223, '684', 'Rauma');
INSERT INTO code_lists.finnish_municipality_codes VALUES (224, '686', 'Rautalampi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (225, '687', 'Rautavaara');
INSERT INTO code_lists.finnish_municipality_codes VALUES (226, '689', 'Rautjärvi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (227, '691', 'Reisjärvi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (228, '694', 'Riihimäki');
INSERT INTO code_lists.finnish_municipality_codes VALUES (229, '697', 'Ristijärvi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (230, '698', 'Rovaniemi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (231, '700', 'Ruokolahti');
INSERT INTO code_lists.finnish_municipality_codes VALUES (232, '702', 'Ruovesi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (233, '704', 'Rusko');
INSERT INTO code_lists.finnish_municipality_codes VALUES (234, '707', 'Rääkkylä');
INSERT INTO code_lists.finnish_municipality_codes VALUES (235, '729', 'Saarijärvi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (236, '732', 'Salla');
INSERT INTO code_lists.finnish_municipality_codes VALUES (237, '734', 'Salo');
INSERT INTO code_lists.finnish_municipality_codes VALUES (238, '736', 'Saltvik');
INSERT INTO code_lists.finnish_municipality_codes VALUES (239, '790', 'Sastamala');
INSERT INTO code_lists.finnish_municipality_codes VALUES (240, '738', 'Sauvo');
INSERT INTO code_lists.finnish_municipality_codes VALUES (241, '739', 'Savitaipale');
INSERT INTO code_lists.finnish_municipality_codes VALUES (242, '740', 'Savonlinna');
INSERT INTO code_lists.finnish_municipality_codes VALUES (243, '742', 'Savukoski');
INSERT INTO code_lists.finnish_municipality_codes VALUES (244, '743', 'Seinäjoki');
INSERT INTO code_lists.finnish_municipality_codes VALUES (245, '746', 'Sievi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (246, '747', 'Siikainen');
INSERT INTO code_lists.finnish_municipality_codes VALUES (247, '748', 'Siikajoki');
INSERT INTO code_lists.finnish_municipality_codes VALUES (248, '791', 'Siikalatva');
INSERT INTO code_lists.finnish_municipality_codes VALUES (249, '749', 'Siilinjärvi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (250, '751', 'Simo');
INSERT INTO code_lists.finnish_municipality_codes VALUES (251, '753', 'Sipoo');
INSERT INTO code_lists.finnish_municipality_codes VALUES (252, '755', 'Siuntio');
INSERT INTO code_lists.finnish_municipality_codes VALUES (253, '758', 'Sodankylä');
INSERT INTO code_lists.finnish_municipality_codes VALUES (254, '759', 'Soini');
INSERT INTO code_lists.finnish_municipality_codes VALUES (255, '761', 'Somero');
INSERT INTO code_lists.finnish_municipality_codes VALUES (256, '762', 'Sonkajärvi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (257, '765', 'Sotkamo');
INSERT INTO code_lists.finnish_municipality_codes VALUES (258, '766', 'Sottunga');
INSERT INTO code_lists.finnish_municipality_codes VALUES (259, '768', 'Sulkava');
INSERT INTO code_lists.finnish_municipality_codes VALUES (260, '771', 'Sund');
INSERT INTO code_lists.finnish_municipality_codes VALUES (261, '777', 'Suomussalmi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (262, '778', 'Suonenjoki');
INSERT INTO code_lists.finnish_municipality_codes VALUES (263, '781', 'Sysmä');
INSERT INTO code_lists.finnish_municipality_codes VALUES (264, '783', 'Säkylä');
INSERT INTO code_lists.finnish_municipality_codes VALUES (265, '831', 'Taipalsaari');
INSERT INTO code_lists.finnish_municipality_codes VALUES (266, '832', 'Taivalkoski');
INSERT INTO code_lists.finnish_municipality_codes VALUES (267, '833', 'Taivassalo');
INSERT INTO code_lists.finnish_municipality_codes VALUES (268, '834', 'Tammela');
INSERT INTO code_lists.finnish_municipality_codes VALUES (269, '837', 'Tampere');
INSERT INTO code_lists.finnish_municipality_codes VALUES (270, '844', 'Tervo');
INSERT INTO code_lists.finnish_municipality_codes VALUES (271, '845', 'Tervola');
INSERT INTO code_lists.finnish_municipality_codes VALUES (272, '846', 'Teuva');
INSERT INTO code_lists.finnish_municipality_codes VALUES (273, '848', 'Tohmajärvi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (274, '849', 'Toholampi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (275, '850', 'Toivakka');
INSERT INTO code_lists.finnish_municipality_codes VALUES (276, '851', 'Tornio');
INSERT INTO code_lists.finnish_municipality_codes VALUES (277, '853', 'Turku');
INSERT INTO code_lists.finnish_municipality_codes VALUES (278, '857', 'Tuusniemi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (279, '858', 'Tuusula');
INSERT INTO code_lists.finnish_municipality_codes VALUES (280, '859', 'Tyrnävä');
INSERT INTO code_lists.finnish_municipality_codes VALUES (281, '886', 'Ulvila');
INSERT INTO code_lists.finnish_municipality_codes VALUES (282, '887', 'Urjala');
INSERT INTO code_lists.finnish_municipality_codes VALUES (283, '889', 'Utajärvi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (284, '890', 'Utsjoki');
INSERT INTO code_lists.finnish_municipality_codes VALUES (285, '892', 'Uurainen');
INSERT INTO code_lists.finnish_municipality_codes VALUES (286, '893', 'Uusikaarlepyy');
INSERT INTO code_lists.finnish_municipality_codes VALUES (287, '895', 'Uusikaupunki');
INSERT INTO code_lists.finnish_municipality_codes VALUES (288, '785', 'Vaala');
INSERT INTO code_lists.finnish_municipality_codes VALUES (289, '905', 'Vaasa');
INSERT INTO code_lists.finnish_municipality_codes VALUES (290, '908', 'Valkeakoski');
INSERT INTO code_lists.finnish_municipality_codes VALUES (291, '092', 'Vantaa');
INSERT INTO code_lists.finnish_municipality_codes VALUES (292, '915', 'Varkaus');
INSERT INTO code_lists.finnish_municipality_codes VALUES (293, '918', 'Vehmaa');
INSERT INTO code_lists.finnish_municipality_codes VALUES (294, '921', 'Vesanto');
INSERT INTO code_lists.finnish_municipality_codes VALUES (295, '922', 'Vesilahti');
INSERT INTO code_lists.finnish_municipality_codes VALUES (296, '924', 'Veteli');
INSERT INTO code_lists.finnish_municipality_codes VALUES (297, '925', 'Vieremä');
INSERT INTO code_lists.finnish_municipality_codes VALUES (298, '927', 'Vihti');
INSERT INTO code_lists.finnish_municipality_codes VALUES (299, '931', 'Viitasaari');
INSERT INTO code_lists.finnish_municipality_codes VALUES (300, '934', 'Vimpeli');
INSERT INTO code_lists.finnish_municipality_codes VALUES (301, '935', 'Virolahti');
INSERT INTO code_lists.finnish_municipality_codes VALUES (302, '936', 'Virrat');
INSERT INTO code_lists.finnish_municipality_codes VALUES (303, '941', 'Vårdö');
INSERT INTO code_lists.finnish_municipality_codes VALUES (304, '946', 'Vöyri');
INSERT INTO code_lists.finnish_municipality_codes VALUES (305, '976', 'Ylitornio');
INSERT INTO code_lists.finnish_municipality_codes VALUES (306, '977', 'Ylivieska');
INSERT INTO code_lists.finnish_municipality_codes VALUES (307, '980', 'Ylöjärvi');
INSERT INTO code_lists.finnish_municipality_codes VALUES (308, '981', 'Ypäjä');
INSERT INTO code_lists.finnish_municipality_codes VALUES (309, '989', 'Ähtäri');
INSERT INTO code_lists.finnish_municipality_codes VALUES (310, '992', 'Äänekoski');

INSERT INTO code_lists.finnish_numeric_value VALUES (1, 1, 'Rakennusoikeus kerrosalaneliömetreinä', '1,2');
INSERT INTO code_lists.finnish_numeric_value VALUES (2, 2, 'Rakennusoikeus murtolukuna', '1,2');
INSERT INTO code_lists.finnish_numeric_value VALUES (3, 4, 'Kerrosluku', '1,2');
INSERT INTO code_lists.finnish_numeric_value VALUES (4, 5, 'Kattokaltevuus', '2');
INSERT INTO code_lists.finnish_numeric_value VALUES (5, 6, 'Sallittu asuinhuoneistojen osuus rakennusalasta', '2');
INSERT INTO code_lists.finnish_numeric_value VALUES (6, 7, 'Salittu myymälätilojen osuus rakennusalasta', '2');
INSERT INTO code_lists.finnish_numeric_value VALUES (7, 8, 'Osuus, jonka rakennuksen suurimman kerroksen alasta saa kellarikerroksessa käyttää kerrosalaan luettavaksi tilaksi', '2');
INSERT INTO code_lists.finnish_numeric_value VALUES (8, 9, 'Osuus, jonka rakennuksen suurimman kerroksen alasta saa käyttää ullakon tasolla kerrosalaan luettavaksi tilaksi', '2');
INSERT INTO code_lists.finnish_numeric_value VALUES (9, 10, 'Luku osoittaa neliömetreinä, kuinka suuren osan rakennuksen alimmasta kerroksesta (I) saa kerroalaneliömetreinä ilmoitetun kerrosalan lisäksi käyttää asukkaiden yhteistiloihin', '2');
INSERT INTO code_lists.finnish_numeric_value VALUES (10, 11, 'Velvoitettu päiväkotitilojen osuus alimman kerroksen rakennusalasta', '2');
INSERT INTO code_lists.finnish_numeric_value VALUES (11, 12, 'Maanipinnan likimääräinen korkeusasema', '3');
INSERT INTO code_lists.finnish_numeric_value VALUES (12, 13, 'Rakennuksen vesikaton ylimmän kohdan korkeusasema', '2');
INSERT INTO code_lists.finnish_numeric_value VALUES (13, 14, 'Rakennuksen julkisivupinnan ja vesikaton leikkauskohdan ylin korkeusasema', '2');
INSERT INTO code_lists.finnish_numeric_value VALUES (14, 15, 'Rakennuksen julkisivun enimmäiskorkeus metreinä', '2,3');
INSERT INTO code_lists.finnish_numeric_value VALUES (15, 16, 'Rakennuksen, rakenteiden ja laitteiden ylin korkeusasema', '2');
INSERT INTO code_lists.finnish_numeric_value VALUES (16, 17, 'Kerrosalaneliömetri määrä, jota kohti on rakennettava yksi autopaikka', '2');
INSERT INTO code_lists.finnish_numeric_value VALUES (17, 18, 'Autopaikkojen lukumäärä asuntoa kohti', '2');
INSERT INTO code_lists.finnish_numeric_value VALUES (18, 19, 'Desibeliraja', '3');
INSERT INTO code_lists.finnish_numeric_value VALUES (19, 20, 'Muu lisärakennusoikeus kerrosalaneliömetreinä', '1,2');
INSERT INTO code_lists.finnish_numeric_value VALUES (20, 3, 'Tehokkuusluku', '1');
INSERT INTO code_lists.finnish_numeric_value VALUES (21, 21, 'Osuus, kuinka suuren osan alueesta tai rakennusalasta saa käyttää rakentamiseen', '2');

INSERT INTO code_lists.finnish_ordinance_process VALUES (1, 1, 'Uusi asemakaava');
INSERT INTO code_lists.finnish_ordinance_process VALUES (2, 2, 'Asemakaavan muutos');
INSERT INTO code_lists.finnish_ordinance_process VALUES (3, 3, 'Uusi ranta-asemakaava');
INSERT INTO code_lists.finnish_ordinance_process VALUES (4, 4, 'Ranta-asemakaavan muutos');

INSERT INTO code_lists.finnish_ordinance_process_step VALUES (1, 1, 'Aloitusvaihe');
INSERT INTO code_lists.finnish_ordinance_process_step VALUES (2, 2, 'Valmisteluvaihe');
INSERT INTO code_lists.finnish_ordinance_process_step VALUES (3, 3, 'Ehdotusvaihe');
INSERT INTO code_lists.finnish_ordinance_process_step VALUES (4, 4, 'Hyväksymisvaihe');
INSERT INTO code_lists.finnish_ordinance_process_step VALUES (5, 5, 'Voimaantulo');
INSERT INTO code_lists.finnish_ordinance_process_step VALUES (6, 6, 'Kumoaminen');
INSERT INTO code_lists.finnish_ordinance_process_step VALUES (7, 7, 'Raukeaminen');

INSERT INTO code_lists.finnish_plan_description VALUES (1, '1', 'Tiivistelmä');
INSERT INTO code_lists.finnish_plan_description VALUES (2, '2', 'Lähtökohdat');
INSERT INTO code_lists.finnish_plan_description VALUES (3, '2A', 'Selvitys suunnittelualueen oloista');
INSERT INTO code_lists.finnish_plan_description VALUES (4, '2B', 'Suunnittelutilanne');
INSERT INTO code_lists.finnish_plan_description VALUES (5, '3', 'Suunnittelun vaiheet');
INSERT INTO code_lists.finnish_plan_description VALUES (6, '3A', 'Kaavan suunnittelun tarve');
INSERT INTO code_lists.finnish_plan_description VALUES (7, '3B', 'Suunnittelun käynnistäminen ja sitä koskevat päätökset');
INSERT INTO code_lists.finnish_plan_description VALUES (8, '3C', 'Osallistuminen ja yhteistyö');
INSERT INTO code_lists.finnish_plan_description VALUES (9, '3D', 'Kaavan tavoitteet');
INSERT INTO code_lists.finnish_plan_description VALUES (10, '3E', 'Kaavaratkaisun vaihtoehdot');
INSERT INTO code_lists.finnish_plan_description VALUES (11, '4', 'Kaavan kuvaus');
INSERT INTO code_lists.finnish_plan_description VALUES (12, '4A', 'Kaavan rakenne');
INSERT INTO code_lists.finnish_plan_description VALUES (13, '4B', 'Aluevaraukset');
INSERT INTO code_lists.finnish_plan_description VALUES (14, '4C', 'Nimistö');
INSERT INTO code_lists.finnish_plan_description VALUES (15, '5', 'Kaavan vaikutukset');
INSERT INTO code_lists.finnish_plan_description VALUES (16, '5A', 'Vaikutukset rakennettuun ympäristöön');
INSERT INTO code_lists.finnish_plan_description VALUES (17, '5B', 'Vaikutukset luontoon ja luonnon ympäristöön');
INSERT INTO code_lists.finnish_plan_description VALUES (18, '5C', 'Muut vaikutukset');
INSERT INTO code_lists.finnish_plan_description VALUES (19, '5D', 'Ympäristön häiriötekijät');
INSERT INTO code_lists.finnish_plan_description VALUES (20, '6', 'Kaavan toteutus');
INSERT INTO code_lists.finnish_plan_description VALUES (21, '6A', 'Toteutusta ohjaavat ja havainnollistavat suunnitelmat');
INSERT INTO code_lists.finnish_plan_description VALUES (22, '6B', 'Toteuttaminen ja ajoitus');
INSERT INTO code_lists.finnish_plan_description VALUES (23, '6C', 'Toteutuksen seuranta');

INSERT INTO code_lists.finnish_planned_space_type VALUES (1, 1, 'Rakennusala');
INSERT INTO code_lists.finnish_planned_space_type VALUES (2, 2, 'Osa-alue');

INSERT INTO code_lists.finnish_planning_detail_line_type VALUES (1, 1, 'Melusuojaustarve');
INSERT INTO code_lists.finnish_planning_detail_line_type VALUES (2, 2, 'Liittymäkielto');
INSERT INTO code_lists.finnish_planning_detail_line_type VALUES (3, 3, 'Harjasuunta');
INSERT INTO code_lists.finnish_planning_detail_line_type VALUES (4, 4, 'Ulkoilureitti');
INSERT INTO code_lists.finnish_planning_detail_line_type VALUES (5, 5, 'Puurivi');
INSERT INTO code_lists.finnish_planning_detail_line_type VALUES (6, 6, 'Rakennusalan sivu, johon kohdistuu lisätieto');
INSERT INTO code_lists.finnish_planning_detail_line_type VALUES (7, 7, 'Muu');

INSERT INTO code_lists.finnish_planning_detail_point_type VALUES (1, 1, 'Ajoneuvoliittymän likimääräinen sijainti');
INSERT INTO code_lists.finnish_planning_detail_point_type VALUES (2, 3, 'Suojeltava puu');
INSERT INTO code_lists.finnish_planning_detail_point_type VALUES (3, 4, 'Maanpinnan likimääräinen korkeusasema');
INSERT INTO code_lists.finnish_planning_detail_point_type VALUES (4, 2, 'Rakennuksen sivu, johon rakennus on rakennettava kiinni');
INSERT INTO code_lists.finnish_planning_detail_point_type VALUES (5, 5, 'Muu');

INSERT INTO code_lists.finnish_regulative_text_type VALUES (1, 33, 'Alueen osa, jolla sijaitsee luonnonsuojelulain mukainen luonnonsuojelualue tai -kohde');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (2, 34, 'Suojeltava rakennus');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (3, 1, 'Tekstimääräys');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (4, 2, 'Auton säilytyspaikan rakennusala');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (5, 3, 'Pysäköimispaikka');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (6, 5, 'Rakennukseen jätettävä kulkuaukko');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (7, 6, 'Maanalaisiin tiloihin johtava ajoliuska');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (8, 7, 'Maanalainen tila');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (9, 8, 'Maanalainen väestönsuojaksi tarkoitettu tila');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (10, 9, 'Maanalainen yleinen pysäköintilaitos');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (11, 10, 'Liikennetunneli');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (12, 11, 'Rakennusala, jolle saa sijoittaa lasten päiväkodin');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (13, 12, 'Rakennusala, jolle saa sijoittaa myymälän');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (14, 13, 'Rakennusala, jolle saa sijoittaa maatilan talouskeskuksen');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (15, 14, 'Rakennusala, jolle saa sijoittaa talousrakennuksen');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (16, 15, 'Alue, jolle saa sijoittaa polttoaineen jakeluaseman');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (17, 16, 'Uloke');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (18, 17, 'Valokatteinen tila');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (19, 18, 'Leikki- ja oleskelualueksi varattu alueen osa');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (20, 19, 'Jalankululle ja polkupyöräilylle varattu alueen osa');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (21, 20, 'Jalankululle ja polkupyöräilylle varattu alueen osa, jolla huoltoajo on sallittu');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (22, 21, 'Jalankululle ja polkupyöräilylle varattu alueen osa, jolla tontille/rakennuspaikalle ajo on sallittu');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (23, 22, 'Yleiseen tiehen kuuluva jalankulku- ja polkupyörätie');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (24, 23, 'Joukkoliikenteelle varattu katu/tie');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (25, 24, 'Ajoyhteys');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (26, 25, 'Alueen sisäiselle huoltoliikenteelle varattu alueen osa');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (27, 26, 'Yleisen tien suoja-alueeksi varattu alueen osa');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (28, 27, 'Yleisen tien  näkemäalueksi varattu alueen osa');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (29, 28, 'Maanalaista johtoa varten varattu alueen osa');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (30, 29, 'Alue on varattu kunnan tarpeisiin');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (31, 30, 'Alue on varattu valtion tarpeisiin');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (32, 31, 'Yhteiskäyttöalue');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (33, 32, 'Suojeltava alueen osa');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (34, 35, 'Rakennussuojelulain nojalla suojeltu rakennus');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (35, 36, 'Maan päällistä johtoa varten varattu alueen osa');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (36, 37, 'Johtoa varten varattu alueen osa');
INSERT INTO code_lists.finnish_regulative_text_type VALUES (37, 4, 'Istutettava alueen osa');

INSERT INTO code_lists.finnish_spatial_plan_approved_by VALUES (1, 1, 'Kunnanvaltuusto');
INSERT INTO code_lists.finnish_spatial_plan_approved_by VALUES (2, 2, 'Kunnanhallitus');
INSERT INTO code_lists.finnish_spatial_plan_approved_by VALUES (3, 3, 'Jaosto/lautakunta');

INSERT INTO code_lists.finnish_spatial_plan_level VALUES (1, 4, 'Asemakaava (ohjeellinen tonttijako)');
INSERT INTO code_lists.finnish_spatial_plan_level VALUES (2, 5, 'Asemakaava (sitova tonttijako)');

INSERT INTO code_lists.finnish_spatial_plan_origin VALUES (1, 1, 'Tietomallin mukaan laadittu', '01');
INSERT INTO code_lists.finnish_spatial_plan_origin VALUES (2, 2, 'Kokonaan digitoitu', '02');
INSERT INTO code_lists.finnish_spatial_plan_origin VALUES (3, 3, 'Osittain digitoitu', '03');
INSERT INTO code_lists.finnish_spatial_plan_origin VALUES (4, 4, 'Kaavan rajaus digitoitu', '04');

INSERT INTO code_lists.finnish_spatial_plan_status VALUES (1, 1, 'Kaavoitusaloite', '01');
INSERT INTO code_lists.finnish_spatial_plan_status VALUES (2, 2, 'Vireilletullut', '02');
INSERT INTO code_lists.finnish_spatial_plan_status VALUES (3, 3, 'Valmisteluaineisto', '03');
INSERT INTO code_lists.finnish_spatial_plan_status VALUES (4, 4, 'Kaavaehdotus', '04');
INSERT INTO code_lists.finnish_spatial_plan_status VALUES (5, 5, 'Hyväksytty kaava', '06');
INSERT INTO code_lists.finnish_spatial_plan_status VALUES (6, 6, 'Voimassa', '10');
INSERT INTO code_lists.finnish_spatial_plan_status VALUES (7, 7, 'Kumoutunut', '12');
INSERT INTO code_lists.finnish_spatial_plan_status VALUES (8, 8, 'Rauennut', '13');
INSERT INTO code_lists.finnish_spatial_plan_status VALUES (9, 9, 'Tarkistettu kaavaehdotus', '05');
INSERT INTO code_lists.finnish_spatial_plan_status VALUES (10, 10, 'Oikaisukehotuksen alainen', '07');
INSERT INTO code_lists.finnish_spatial_plan_status VALUES (11, 11, 'Valituksenalainen', '08');
INSERT INTO code_lists.finnish_spatial_plan_status VALUES (12, 12, 'Osittain voimassa', '09');
INSERT INTO code_lists.finnish_spatial_plan_status VALUES (13, 13, 'Kumottu', '11');
INSERT INTO code_lists.finnish_spatial_plan_status VALUES (14, 14, 'Hylätty', '14');

INSERT INTO code_lists.finnish_spatial_plan_type VALUES (1, 1, 'Asemakaava', '31');
INSERT INTO code_lists.finnish_spatial_plan_type VALUES (2, 2, 'Ranta-asemakaava', '33');
INSERT INTO code_lists.finnish_spatial_plan_type VALUES (3, 3, 'Vaiheasemakaava', '32');
INSERT INTO code_lists.finnish_spatial_plan_type VALUES (4, 4, 'Vaiheranta-asemakaava', '34');
INSERT INTO code_lists.finnish_spatial_plan_type VALUES (5, 5, 'Maanalaisten tilojen asemakaava', '35');

INSERT INTO code_lists.finnish_up_to_dateness VALUES (1, 1, 'Kaava vanhentunut');
INSERT INTO code_lists.finnish_up_to_dateness VALUES (2, 2, 'Ajanmukainen');
INSERT INTO code_lists.finnish_up_to_dateness VALUES (3, 3, 'Päätös vanhentunut');
INSERT INTO code_lists.finnish_up_to_dateness VALUES (4, 4, 'Arviointi vireillä');

INSERT INTO code_lists.finnish_vertical_coordinate_reference_system VALUES (1, 1, 'N2000');
INSERT INTO code_lists.finnish_vertical_coordinate_reference_system VALUES (2, 2, 'N60');
INSERT INTO code_lists.finnish_vertical_coordinate_reference_system VALUES (3, 3, 'N43');
INSERT INTO code_lists.finnish_vertical_coordinate_reference_system VALUES (4, 4, 'NN');

INSERT INTO code_lists.finnish_zoning_element_type VALUES (1, 1, 'Pääkäyttötarkoitusalue');
INSERT INTO code_lists.finnish_zoning_element_type VALUES (2, 2, 'Sitova tontti');
INSERT INTO code_lists.finnish_zoning_element_type VALUES (3, 3, 'Ohjeellinen tontti');

INSERT INTO code_lists.validity_type VALUES (1, 1, 'Täysin voimassa');
INSERT INTO code_lists.validity_type VALUES (2, 2, 'Osittain voimassa');
INSERT INTO code_lists.validity_type VALUES (3, 3, 'Ei voimassa');
INSERT INTO code_lists.validity_type VALUES (4, 4, 'Keskeneräinen');

SELECT pg_catalog.setval('code_lists.describing_line_type_identifier_seq', 5, true);
SELECT pg_catalog.setval('code_lists.finnish_area_type_identifier_seq', 3, true);
SELECT pg_catalog.setval('code_lists.finnish_document_role_identifier_seq', 4, true);
SELECT pg_catalog.setval('code_lists.finnish_document_type_identifier_seq', 1, false);
SELECT pg_catalog.setval('code_lists.finnish_informative_feature_type_identifier_seq', 12, true);
SELECT pg_catalog.setval('code_lists.finnish_land_use_kind_identifier_seq', 121, true);
SELECT pg_catalog.setval('code_lists.finnish_language_identifier_seq', 1, false);
SELECT pg_catalog.setval('code_lists.finnish_municipality_codes_identifier_seq', 1, false);
SELECT pg_catalog.setval('code_lists.finnish_numeric_value_identifier_seq', 21, true);
SELECT pg_catalog.setval('code_lists.finnish_ordinance_process_identifier_seq', 4, true);
SELECT pg_catalog.setval('code_lists.finnish_ordinance_process_step_identifier_seq', 7, true);
SELECT pg_catalog.setval('code_lists.finnish_plan_description_identifier_seq', 23, true);
SELECT pg_catalog.setval('code_lists.finnish_planned_space_type_identifier_seq', 2, true);
SELECT pg_catalog.setval('code_lists.finnish_planning_detail_line_type_identifier_seq', 7, true);
SELECT pg_catalog.setval('code_lists.finnish_planning_detail_point_type_identifier_seq', 5, true);
SELECT pg_catalog.setval('code_lists.finnish_regulative_text_type_identifier_seq', 37, true);
SELECT pg_catalog.setval('code_lists.finnish_spatial_plan_approved_by_identifier_seq', 3, true);
SELECT pg_catalog.setval('code_lists.finnish_spatial_plan_level_identifier_seq', 2, true);
SELECT pg_catalog.setval('code_lists.finnish_spatial_plan_origin_identifier_seq', 4, true);
SELECT pg_catalog.setval('code_lists.finnish_spatial_plan_status_identifier_seq', 14, true);
SELECT pg_catalog.setval('code_lists.finnish_spatial_plan_type_identifier_seq', 5, true);
SELECT pg_catalog.setval('code_lists.finnish_up_to_dateness_identifier_seq', 4, true);
SELECT pg_catalog.setval('code_lists.finnish_vertical_coordinate_reference_system_identifier_seq', 4, true);
SELECT pg_catalog.setval('code_lists.finnish_zoning_element_type_identifier_seq', 3, true);
SELECT pg_catalog.setval('code_lists.validity_type_identifier_seq', 1, false);