CORE_NS = "lud-core"
SPLAN_NS = "splan"

# lud-core tags
FEATUREMEMBER = CORE_NS + ":featureMember"
PRODUCER_SPECIFIC_IDENTIFIER = CORE_NS + ":producerSpecificIdentifier"
OBJECT_IDENTIFIER = CORE_NS + ":objectIdentifier"
LATEST_CHANGE = CORE_NS + ":latestChange"
STORAGE_TIME = CORE_NS + ":storageTime"
NAME = CORE_NS + ":loc_name"
BOUNDARY = CORE_NS + ":boundary"
LEGAL_EFFECTIVENESS = CORE_NS + ":legalEffectiveness"
RESPONSIBLE_ORGANIZATION = CORE_NS + ":responsibleOrganization"
VALIDITY_TIME = CORE_NS + ":validityTime"
ANNEX = CORE_NS + ":annex"
DOCUMENT = CORE_NS + ":Document"
CORE_TYPE = CORE_NS + ":type"
ADDITIONAL_INFORMATION_LINK = CORE_NS + ":additionalInformationLink"
CODE_SPACE = "http://uri.suomi.fi/object/rytj/kaava"

# splan tags
SPATIAL_PLAN = SPLAN_NS + ":SpatialPlan"
SPATIAL_PLAN_REF = SPLAN_NS + ":spatialPlan"
VALIDITY_TIME_INSIDE_SPLAN = SPLAN_NS + ":validityTime"
PLAN_IDENTIFIER = SPLAN_NS + ":planIdentifier"
INITIATION_TIME = SPLAN_NS + ":initiationTime"
APPROVAL_TIME = SPLAN_NS + ":approvalTime"
DIGITAL_ORIGIN = SPLAN_NS + ":digitalOrigin"
NAME_INSIDE_SPLAN = SPLAN_NS + ":loc_name"
PLAN_IDENTIFIER = SPLAN_NS + ":planIdentifier"
PLAN_OBJECT = SPLAN_NS + ":PlanObject"
PLAN_ORDER = SPLAN_NS + ":PlanOrder"
GENERAL_ORDER = SPLAN_NS + ":generalOrder"
PLAN_RECOMMENDATION = SPLAN_NS + ":PlanRecommendation"
GENERAL_RECOMMENDATION = SPLAN_NS + ":generalRecommendation"
VALUE = SPLAN_NS + ":value"
PLAN_ORDER_GROUP = SPLAN_NS + ":PlanOrderGroup"
SUPPLEMENTARY_INFO = SPLAN_NS + ":supplementaryInfo"
SUPPLEMENTARY_INFORMATION = SPLAN_NS + ":SupplementaryInformation"
TARGET = SPLAN_NS + ":target"
MEMBER = SPLAN_NS + ":member"
GROUP_NUMBER = SPLAN_NS + ":groupNumber"
GEOMETRY = SPLAN_NS + ":geometry"
GROUND_RELATIVE_POSITION = SPLAN_NS + ":groundRelativePosition"
BINDINGNESS_OF_LOCATION = SPLAN_NS + ":bindingnessOfLocation"
TYPE = SPLAN_NS + ":type"
LIFECYCLE_STATUS = SPLAN_NS + ":lifecycleStatus"
COMMENTARY = SPLAN_NS + ":SpatialPlanCommentary"
PARTICIPATION_AND_EVALUATION_PLAN = SPLAN_NS + ":ParticipationAndEvaluationPlan"
PARTICIPATION_AND_EVALUATION_PLAN_REF = SPLAN_NS + ":participationAndEvalutionPlan"
PLANNER = SPLAN_NS + ":Planner"
PLANNER_REF = SPLAN_NS + ":planner"
PERSON_NAME = SPLAN_NS + ":personName"
PROFESSION_TITLE = SPLAN_NS + ":professionTitle"
ROLE = SPLAN_NS + ":role"
DOCUMENT_INSIDE_SPLAN = SPLAN_NS + ":document"
RELATED_DOCUMENT = SPLAN_NS + ":relatedDocument"

# values
CODE_VALUE = SPLAN_NS + ":CodeValue"
GEOMETRY_VALUE = SPLAN_NS + ":GeometryValue"
IDENTITY_VALUE = SPLAN_NS + ":IdentityValue"
NUMERIC_VALUE = SPLAN_NS + ":NumericValue"
NUMERIC_RANGE_VALUE = SPLAN_NS + ":NumericRange"
TEXT_VALUE = SPLAN_NS + ":TextValue"
TIME_INSTANT_VALUE = SPLAN_NS + ":TimeInstantValue"
TIME_PERIOD_VALUE = SPLAN_NS + ":TimePeriodValue"

# GML tags
GML_POINT = "gml:Point"
GML_LINESTRING = "gml:LineString"
GML_POLYGON = "gml:Polygon"
GML_EXTERIOR = "gml:exterior"
GML_LINEAR_RING = "gml:LinearRing"
POS = "pos"
POS_LIST = "posList"
TIME_INSTANT = "gml:TimeInstant"
TIME_POSITION = "gml:timePosition"
TIME_PERIOD = "gml:TimePeriod"
BEGIN_POSITION = "gml:beginPosition"
END_POSITION = "gml:endPosition"
REFERENCE_IDENTIFIER = "gml:identifier"
