CREATE OR REPLACE FUNCTION SCHEMANAME.refresh_plan_regulations_point_view()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
    BEGIN REFRESH MATERIALIZED VIEW SCHEMANAME.plan_regulations_point_view;
    RETURN NULL;
END $$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION SCHEMANAME.refresh_plan_regulations_line_view()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN REFRESH MATERIALIZED VIEW SCHEMANAME.plan_regulations_line_view;
RETURN NULL;
END $$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION SCHEMANAME.refresh_plan_regulations_area_view()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN REFRESH MATERIALIZED VIEW SCHEMANAME.plan_regulations_area_view;
RETURN NULL;
END $$ SECURITY DEFINER;
