-- Drop roles
DROP ROLE IF EXISTS qgis_admin_$MUNICIPALITYCODE$;
DROP ROLE IF EXISTS qgis_editor_$MUNICIPALITYCODE$;

-- Create roles
CREATE ROLE qgis_admin_$MUNICIPALITYCODE$;
CREATE ROLE qgis_editor_$MUNICIPALITYCODE$;

-- Grant privileges to qgis_admin_$MUNICIPALITYCODE$
GRANT USAGE ON SCHEMA code_lists, public, $SCHEMANAME$ TO qgis_admin_$MUNICIPALITYCODE$;
GRANT SELECT ON ALL TABLES IN SCHEMA code_lists, $SCHEMANAME$ TO qgis_admin_$MUNICIPALITYCODE$;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA $SCHEMANAME$ TO qgis_admin_$MUNICIPALITYCODE$;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA $SCHEMANAME$ TO qgis_admin_$MUNICIPALITYCODE$;
GRANT SELECT, INSERT, UPDATE ON public.qgis_projects TO qgis_admin_$MUNICIPALITYCODE$;

-- Grant privileges to qgis_editor_$MUNICIPALITYCODE$
GRANT USAGE ON SCHEMA code_lists, public, $SCHEMANAME$ TO qgis_editor_$MUNICIPALITYCODE$;
GRANT SELECT ON ALL TABLES IN SCHEMA code_lists, $SCHEMANAME$ TO qgis_editor_$MUNICIPALITYCODE$;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA $SCHEMANAME$ TO qgis_editor_$MUNICIPALITYCODE$;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA $SCHEMANAME$ TO qgis_editor_$MUNICIPALITYCODE$;
GRANT SELECT ON public.qgis_projects TO qgis_editor_$MUNICIPALITYCODE$;
