CREATE TABLE code_lists.master_plan_envrionmental_change_kind (
  id SERIAL PRIMARY KEY,
  codevalue VARCHAR(3) NOT NULL UNIQUE,
  uri VARCHAR(255) NOT NULL UNIQUE,
  preflabel_fi VARCHAR NOT NULL,
  preflabel_sv VARCHAR,
  description_fi VARCHAR,
  description_sv VARCHAR
);

CREATE TRIGGER upsert_master_plan_envrionmental_change_kind
  BEFORE INSERT OR UPDATE ON code_lists.master_plan_envrionmental_change_kind
  FOR EACH ROW EXECUTE PROCEDURE code_lists.code_url_trigger('http://uri.suomi.fi/codelist/rytj/RY_ymparistomuutoksenLaji_YK/code/');

INSERT INTO code_lists.master_plan_envrionmental_change_kind (codevalue, preflabel_fi, description_fi)
VALUES
  ('01', 'Olemassa oleva', 'Kaavakohde kuvaa kaavan laatimisen hetkellä olemassa olevaa kohdetta. Tällaisia voivat esimerkiksi olla olemassa olevat (jo rakennetut) rakennuspaikat, väylät tai muut kohteet.'),
  ('02', 'Uusi', 'Kaavakohde on uusi eli sitä ei vielä ole toteutettu. Koodiarvolla voidaan ilmaista esimerkiksi uusi rakennuspaikka, uusi väylä tai muu kaavakohde.');

CREATE TABLE code_lists.master_plan_theme (
  id SERIAL PRIMARY KEY,
  codevalue VARCHAR(3) NOT NULL UNIQUE,
  uri VARCHAR(255) NOT NULL UNIQUE,
  preflabel_fi VARCHAR NOT NULL,
  preflabel_sv VARCHAR,
  definition_fi VARCHAR,
  definition_sv VARCHAR
);

CREATE TRIGGER upsert_master_plan_theme
  BEFORE INSERT OR UPDATE ON code_lists.master_plan_theme
  FOR EACH ROW EXECUTE PROCEDURE code_lists.code_url_trigger('http://uri.suomi.fi/codelist/rytj/RY_Kaavoitusteema_YK/code/');

INSERT INTO code_lists.master_plan_theme (codevalue, preflabel_sv, preflabel_fi, definition_fi)
VALUES
  ('01', 'Samhällsstruktur', 'Yhdyskuntarakenne', 'Kaupunkiseudun, kunnan tai kunnan osan keskeisten toimintojen sijoittuminen ja keskinäiset suhteet'),
  ('02', 'Trafiknät', 'Liikenneverkko', 'Eri liikennemuotoja palvelevat väylät ja näiden solmukohdat'),
  ('03', NULL, 'Luontoarvot', 'Arvo, joka perustuu bio- ja geodiversiteettiin jollakin tietyllä alueella'),
  ('04', 'Grönnät', 'Viherverkko', 'Viheralueiden ja niitä yhdistävien viheryhteyksien muodostama kokonaisuus'),
  ('05', NULL, 'Virkistysalueet', 'Virkistykseen ja ulkoiluun varatut alueet'),
  ('06', 'Kulturmiljö', 'Kulttuuriympäristö', 'Kulttuurin vaiheita sekä ihmisen ja luonnon vuorovaikutusta ilmentävä ympäristö'),
  ('07', NULL, 'Yhdyskuntatekninen huolto', 'Yhdyskunnan yleistä tarvetta palvelevat verkostot ja rakenteet'),
  ('08', NULL, 'Vesitalous', 'Toiminta, jolla pyritään vesivarojen tarkoituksenmukaiseen hyväksikäyttöön ja suojeluun'),
  ('09', NULL, 'Muu kaavoitusteema', NULL);

CREATE TABLE code_lists.master_plan_regulation_kind (
  id SERIAL PRIMARY KEY,
  codevalue VARCHAR(6) NOT NULL UNIQUE,
  uri VARCHAR(255) NOT NULL UNIQUE,
  preflabel_fi VARCHAR NOT NULL,
  definition_fi VARCHAR,
  description_fi VARCHAR,
  main_class VARCHAR NOT NULL,
  sub_class VARCHAR
);

CREATE TRIGGER upsert_master_plan_regulation_kind
  BEFORE INSERT OR UPDATE ON code_lists.master_plan_regulation_kind
  FOR EACH ROW EXECUTE PROCEDURE code_lists.code_url_trigger('http://uri.suomi.fi/codelist/rytj/RY_KaavamaaraysLaji_YK/code/');


INSERT INTO code_lists.master_plan_regulation_kind (codevalue, main_class, sub_class, preflabel_fi, definition_fi, description_fi)
VALUES
  ('01','Alueen käyttötarkoitus',NULL,'Alueen käyttötarkoitus',NULL,NULL),
  ('0101','Alueen käyttötarkoitus','Asuminen','Asuminen',NULL,NULL),
  ('010101','Alueen käyttötarkoitus','Asuminen','Asuinkerrostaloalue',NULL,NULL),
  ('010102','Alueen käyttötarkoitus','Asuminen','Asuinpientaloalue',NULL,NULL),
  ('010103','Alueen käyttötarkoitus','Asuminen','Rivitalojen ja muiden kytkettyjen asuinrakennusten alue',NULL,NULL),
  ('010104','Alueen käyttötarkoitus','Asuminen','Erillispientaloalue',NULL,NULL),
  ('010105','Alueen käyttötarkoitus','Asuminen','Asumista palveleva yhteiskäyttöinen alue',NULL,NULL),
  ('010106','Alueen käyttötarkoitus','Asuminen','Maatilan talouskeskuksen alue',NULL,NULL),
  ('010107','Alueen käyttötarkoitus','Asuminen','Kyläalue',NULL,NULL),
  ('010108','Alueen käyttötarkoitus','Asuminen','Erityisryhmien palveluasuminen',NULL,NULL),
  ('010109','Alueen käyttötarkoitus','Asuminen','Muu asuminen',NULL,NULL),
  ('0102','Alueen käyttötarkoitus','Keskustatoiminnot','Keskustatoiminnot',NULL,NULL),
  ('010201','Alueen käyttötarkoitus','Keskustatoiminnot','Keskustatoimintojen alue',NULL,NULL),
  ('010202','Alueen käyttötarkoitus','Keskustatoiminnot','Keskustatoimintojen alakeskus',NULL,NULL),
  ('010203','Alueen käyttötarkoitus','Keskustatoiminnot','Muut keskustatoiminnot',NULL,NULL),
  ('0103','Alueen käyttötarkoitus','Elinkeinot, työ ja tuotanto','Elinkeinot, työ ja tuotanto',NULL,NULL),
  ('010301','Alueen käyttötarkoitus','Elinkeinot, työ ja tuotanto','Liikerakennusten alue',NULL,NULL),
  ('010302','Alueen käyttötarkoitus','Elinkeinot, työ ja tuotanto','Toimistorakennusten alue',NULL,NULL),
  ('010303','Alueen käyttötarkoitus','Elinkeinot, työ ja tuotanto','Toimitilarakennusten alue',NULL,NULL),
  ('010304','Alueen käyttötarkoitus','Elinkeinot, työ ja tuotanto','Kaupallisten palveluiden alue',NULL,NULL),
  ('010305','Alueen käyttötarkoitus','Elinkeinot, työ ja tuotanto','Vähittäiskaupan suuryksikkö',NULL,NULL),
  ('010306','Alueen käyttötarkoitus','Elinkeinot, työ ja tuotanto','Vähittäiskaupan myymäläkeskittymä',NULL,NULL),
  ('010307','Alueen käyttötarkoitus','Elinkeinot, työ ja tuotanto','Työpaikka-alue',NULL,NULL),
  ('010308','Alueen käyttötarkoitus','Elinkeinot, työ ja tuotanto','Teollisuusalue',NULL,NULL),
  ('010309','Alueen käyttötarkoitus','Elinkeinot, työ ja tuotanto','Varastorakennusten alue',NULL,NULL),
  ('010310','Alueen käyttötarkoitus','Elinkeinot, työ ja tuotanto','Alue, jolle saa sijoittaa merkittävän, vaarallisia kemikaaleja valmistavan tai varastoivan laitoksen',NULL,NULL),
  ('010311','Alueen käyttötarkoitus','Elinkeinot, työ ja tuotanto','Ympäristövaikutuksiltaan merkittävien teollisuustoimintojen alue',NULL,NULL),
  ('010312','Alueen käyttötarkoitus','Elinkeinot, työ ja tuotanto','Kiertotalous',NULL,NULL),
  ('010313','Alueen käyttötarkoitus','Elinkeinot, työ ja tuotanto','Ympäristöhäiriötä aiheuttava tuotantotoiminta',NULL,NULL),
  ('010314','Alueen käyttötarkoitus','Elinkeinot, työ ja tuotanto','Muu elinkeinotoiminta',NULL,NULL),
  ('0104','Alueen käyttötarkoitus','Palvelut','Palvelut',NULL,NULL),
  ('010401','Alueen käyttötarkoitus','Palvelut','Palvelurakennusten alue',NULL,NULL),
  ('010402','Alueen käyttötarkoitus','Palvelut','Lähipalveluiden alue',NULL,NULL),
  ('010403','Alueen käyttötarkoitus','Palvelut','Huvi- ja viihdepalveluiden alue',NULL,NULL),
  ('010404','Alueen käyttötarkoitus','Palvelut','Julkiset palvelut',NULL,NULL),
  ('010405','Alueen käyttötarkoitus','Palvelut','Yleisten rakennusten alue',NULL,NULL),
  ('010406','Alueen käyttötarkoitus','Palvelut','Julkisten lähipalveluiden alue',NULL,NULL),
  ('010407','Alueen käyttötarkoitus','Palvelut','Hallinto- ja virastorakennusten alue',NULL,NULL),
  ('010408','Alueen käyttötarkoitus','Palvelut','Opetustoimintaa palvelevien rakennusten alue',NULL,NULL),
  ('010409','Alueen käyttötarkoitus','Palvelut','Sosiaalitointa ja terveydenhuoltoa palvelevien rakennusten alue',NULL,NULL),
  ('010410','Alueen käyttötarkoitus','Palvelut','Kulttuuritoimintaa palvelevien rakennusten alue',NULL,NULL),
  ('010411','Alueen käyttötarkoitus','Palvelut','Museorakennusten alue',NULL,NULL),
  ('010412','Alueen käyttötarkoitus','Palvelut','Kirkkojen ja muiden seurakunnallisten rakennusten alue',NULL,NULL),
  ('010413','Alueen käyttötarkoitus','Palvelut','Urheilutoimintaa palvelevien rakennusten alue',NULL,NULL),
  ('010414','Alueen käyttötarkoitus','Palvelut','Julkisten palveluiden ja hallinnon alue',NULL,NULL),
  ('010415','Alueen käyttötarkoitus','Palvelut','Muut palvelut',NULL,NULL),
  ('0105','Alueen käyttötarkoitus','Virkistys','Virkistys',NULL,NULL),
  ('010501','Alueen käyttötarkoitus','Virkistys','Virkistysalue',NULL,NULL),
  ('010502','Alueen käyttötarkoitus','Virkistys','Puisto',NULL,NULL),
  ('010503','Alueen käyttötarkoitus','Virkistys','Lähivirkistysalue',NULL,NULL),
  ('010504','Alueen käyttötarkoitus','Virkistys','Leikkipuisto',NULL,NULL),
  ('010505','Alueen käyttötarkoitus','Virkistys','Urheilupalvelujen alue',NULL,NULL),
  ('010506','Alueen käyttötarkoitus','Virkistys','Retkeily- ja ulkoilualue',NULL,NULL),
  ('010507','Alueen käyttötarkoitus','Virkistys','Uimaranta-alue',NULL,NULL),
  ('010508','Alueen käyttötarkoitus','Virkistys','Lähimetsä',NULL,NULL),
  ('010509','Alueen käyttötarkoitus','Virkistys','Muu virkistysalue',NULL,NULL),
  ('0106','Alueen käyttötarkoitus','Loma-asuminen ja matkailu','Loma-asuminen ja matkailu',NULL,NULL),
  ('010601','Alueen käyttötarkoitus','Loma-asuminen ja matkailu','Loma-asuntojen alue',NULL,NULL),
  ('010602','Alueen käyttötarkoitus','Loma-asuminen ja matkailu','Matkailua palvelevien rakennusten alue',NULL,NULL),
  ('010603','Alueen käyttötarkoitus','Loma-asuminen ja matkailu','Leirintäalue',NULL,NULL),
  ('010604','Alueen käyttötarkoitus','Loma-asuminen ja matkailu','Asuntovaunualue',NULL,NULL),
  ('010605','Alueen käyttötarkoitus','Loma-asuminen ja matkailu','Siirtolapuutarha-/palstaviljelyalue',NULL,NULL),
  ('010606','Alueen käyttötarkoitus','Loma-asuminen ja matkailu','Muu loma-asumisen tai matkailun alue',NULL,NULL),
  ('0107','Alueen käyttötarkoitus','Liikenne','Liikenne',NULL,NULL),
  ('010701','Alueen käyttötarkoitus','Liikenne','Liikennealue',NULL,NULL),
  ('010702','Alueen käyttötarkoitus','Liikenne','Yleisen tien alue',NULL,NULL),
  ('010703','Alueen käyttötarkoitus','Liikenne','Rautatieliikenteen alue',NULL,NULL),
  ('010704','Alueen käyttötarkoitus','Liikenne','Lentoliikenteen alue',NULL,NULL),
  ('010705','Alueen käyttötarkoitus','Liikenne','Satama-alue',NULL,NULL),
  ('010706','Alueen käyttötarkoitus','Liikenne','Kanava-alue',NULL,NULL),
  ('010707','Alueen käyttötarkoitus','Liikenne','Venesatama/venevalkama',NULL,NULL),
  ('010708','Alueen käyttötarkoitus','Liikenne','Yleinen pysäköintialue',NULL,NULL),
  ('010709','Alueen käyttötarkoitus','Liikenne','Huoltoasema-alue',NULL,NULL),
  ('010710','Alueen käyttötarkoitus','Liikenne','Henkilöliikenteen terminaalialue',NULL,NULL),
  ('010711','Alueen käyttötarkoitus','Liikenne','Tavaraliikenteen terminaalialue',NULL,NULL),
  ('010712','Alueen käyttötarkoitus','Liikenne','Yleisten pysäköintilaitosten alue',NULL,NULL),
  ('010713','Alueen käyttötarkoitus','Liikenne','Autopaikkojen alue',NULL,NULL),
  ('010714','Alueen käyttötarkoitus','Liikenne','Katualue',NULL,NULL),
  ('010715','Alueen käyttötarkoitus','Liikenne','Muu liikennealue',NULL,NULL),
  ('0108','Alueen käyttötarkoitus','Erityisalueet','Erityisalueet',NULL,NULL),
  ('010801','Alueen käyttötarkoitus','Erityisalueet','Erityisalue',NULL,NULL),
  ('010802','Alueen käyttötarkoitus','Erityisalueet','Yhdyskuntateknisen huollon alue',NULL,NULL),
  ('010803','Alueen käyttötarkoitus','Erityisalueet','Energiahuollon alue',NULL,NULL),
  ('010804','Alueen käyttötarkoitus','Erityisalueet','Jätteenkäsittelyalue',NULL,NULL),
  ('010805','Alueen käyttötarkoitus','Erityisalueet','Maa-ainesten ottoalue',NULL,NULL),
  ('010806','Alueen käyttötarkoitus','Erityisalueet','Kaivosalue',NULL,NULL),
  ('010807','Alueen käyttötarkoitus','Erityisalueet','Mastoalue',NULL,NULL),
  ('010808','Alueen käyttötarkoitus','Erityisalueet','Ampumarata-alue',NULL,NULL),
  ('010809','Alueen käyttötarkoitus','Erityisalueet','Puolustusvoimien alue',NULL,NULL),
  ('010810','Alueen käyttötarkoitus','Erityisalueet','Hautausmaa-alue',NULL,NULL),
  ('010811','Alueen käyttötarkoitus','Erityisalueet','Suojaviheralue',NULL,NULL),
  ('010812','Alueen käyttötarkoitus','Erityisalueet','Tuulivoimaloiden alue',NULL,NULL),
  ('010813','Alueen käyttötarkoitus','Erityisalueet','Moottorirata',NULL,NULL),
  ('010814','Alueen käyttötarkoitus','Erityisalueet','Maa-ainesten vastaanotto- tai läjitysalue',NULL,NULL),
  ('010815','Alueen käyttötarkoitus','Erityisalueet','Vankila-alue',NULL,NULL),
  ('010816','Alueen käyttötarkoitus','Erityisalueet','Muu erityisalue',NULL,NULL),
  ('0109','Alueen käyttötarkoitus','Suojelu','Suojelu',NULL,NULL),
  ('010901','Alueen käyttötarkoitus','Suojelu','Suojelualue',NULL,NULL),
  ('010902','Alueen käyttötarkoitus','Suojelu','Luonnonsuojelualue',NULL,NULL),
  ('010903','Alueen käyttötarkoitus','Suojelu','Muinaismuistoalue',NULL,NULL),
  ('010904','Alueen käyttötarkoitus','Suojelu','Rakennuslainsäädännön nojalla suojeltava alue',NULL,NULL),
  ('010905','Alueen käyttötarkoitus','Suojelu','Rakennussuojelulakien nojalla suojeltu alue',NULL,NULL),
  ('010906','Alueen käyttötarkoitus','Suojelu','Muu suojelualue',NULL,NULL),
  ('0110','Alueen käyttötarkoitus','Maa- ja metsätalous','Maa- ja metsätalous',NULL,NULL),
  ('011001','Alueen käyttötarkoitus','Maa- ja metsätalous','Maa- ja metsätalousalue',NULL,NULL),
  ('011002','Alueen käyttötarkoitus','Maa- ja metsätalous','Maatalousalue',NULL,NULL),
  ('011003','Alueen käyttötarkoitus','Maa- ja metsätalous','Kotieläintalouden suuryksikön alue',NULL,NULL),
  ('011004','Alueen käyttötarkoitus','Maa- ja metsätalous','Puutarha- ja kasvihuonealue',NULL,NULL),
  ('011005','Alueen käyttötarkoitus','Maa- ja metsätalous','Maisemallisesti arvokas peltoalue',NULL,NULL),
  ('011006','Alueen käyttötarkoitus','Maa- ja metsätalous','Poronhoitovaltainen maa- ja metsätalousalue',NULL,NULL),
  ('011007','Alueen käyttötarkoitus','Maa- ja metsätalous','Muu maa- ja metsätalousalue',NULL,NULL),
  ('0111','Alueen käyttötarkoitus','Vesialueet','Vesialueet',NULL,NULL),
  ('011101','Alueen käyttötarkoitus','Vesialueet','Vesialue',NULL,NULL),
  ('011102','Alueen käyttötarkoitus','Vesialueet','Muu vesialue',NULL,NULL),
  ('02','Rakentaminen',NULL,'Rakentaminen',NULL,NULL),
  ('0201','Rakentaminen','Rakennusala','Rakennusala',NULL,NULL),
  ('0202','Rakentaminen','Rakennuspaikka','Rakennuspaikka',NULL,NULL),
  ('0203','Rakentaminen','Asunnon rakennuspaikka','Asunnon rakennuspaikka',NULL,NULL),
  ('0204','Rakentaminen','Loma-asunnon rakennuspaikka','Loma-asunnon rakennuspaikka',NULL,NULL),
  ('0205','Rakentaminen','Saunan rakennuspaikka','Saunan rakennuspaikka',NULL,NULL),
  ('0206','Rakentaminen','Maatalouden talouskeskuksen rakennuspaikka','Maatalouden talouskeskuksen rakennuspaikka',NULL,NULL),
  ('0207','Rakentaminen','Sallittu kokonaiskerrosala','Sallittu kokonaiskerrosala','Kokonaiskerrosalan suhde korttelin pinta-alaan',NULL),
  ('0208','Rakentaminen','Aluetehokkuus','Aluetehokkuus',NULL,NULL),
  ('0209','Rakentaminen','Korttelitehokkuus','Korttelitehokkuus','Kokonaiskerrosalan suhde tontin/rakennuspaikan pinta-alaan',NULL),
  ('0210','Rakentaminen','Tonttitehokkuus','Tonttitehokkuus',NULL,NULL),
  ('0211','Rakentaminen','Sallittujen rakennuspaikkojen lukumäärä','Sallittujen rakennuspaikkojen lukumäärä',NULL,NULL),
  ('0212','Rakentaminen','Rakennuspaikan vähimmäiskoko','Rakennuspaikan vähimmäiskoko',NULL,NULL),
  ('0213','Rakentaminen','Sallittu tuulivoimaloiden määrä','Sallittu tuulivoimaloiden määrä',NULL,NULL),
  ('0214','Rakentaminen','Vähittäiskaupan suuryksikön sallittu kerrosala','Vähittäiskaupan suuryksikön sallittu kerrosala',NULL,NULL),
  ('0215','Rakentaminen','Vähittäiskaupan myymäläkeskittymän sallittu kerrosala','Vähittäiskaupan myymäläkeskittymän sallittu kerrosala',NULL,NULL),
  ('03','Liikenne',NULL,'Liikenne',NULL,NULL),
  ('0301','Liikenne','Alueverkon pyöräilyreitti','Alueverkon pyöräilyreitti',NULL,NULL),
  ('0302','Liikenne','Eritasoliittymä','Eritasoliittymä',NULL,NULL),
  ('0303','Liikenne','Eritasoristeys ilman liittymää','Eritasoristeys ilman liittymää',NULL,NULL),
  ('0304','Liikenne','Joukkoliikenteen runkoyhteys','Joukkoliikenteen runkoyhteys',NULL,NULL),
  ('0305','Liikenne','Kaksiajoratainen päätie/-katu','Kaksiajoratainen päätie/-katu',NULL,NULL),
  ('0306','Liikenne','Kevyen liikenteen reitti','Kevyen liikenteen reitti',NULL,NULL),
  ('0307','Liikenne','Laivaväylä','Laivaväylä',NULL,NULL),
  ('0308','Liikenne','Liikennetunneli','Liikennetunneli',NULL,NULL),
  ('0309','Liikenne','Liittymä','Liittymä',NULL,NULL),
  ('0310','Liikenne','Linja-autoasema/julkisen liikenteen vaihtopaikka/matkakeskus','Linja-autoasema/julkisen liikenteen vaihtopaikka/matkakeskus',NULL,NULL),
  ('0311','Liikenne','Metroasema','Metroasema',NULL,NULL),
  ('0312','Liikenne','Metrolinja','Metrolinja',NULL,NULL),
  ('0313','Liikenne','Moottori- tai moottoriliikennetie','Moottori- tai moottoriliikennetie',NULL,NULL),
  ('0314','Liikenne','Moottorikelkkailureitti','Moottorikelkkailureitti',NULL,NULL),
  ('0315','Liikenne','Pysäkki/seisake','Pysäkki/seisake',NULL,NULL),
  ('0316','Liikenne','Pyöräilyn pää-/runkoreitti','Pyöräilyn pää-/runkoreitti',NULL,NULL),
  ('0317','Liikenne','Päärata','Päärata',NULL,NULL),
  ('0318','Liikenne','Raitiotie/Pikaraitiotie','Raitiotie/Pikaraitiotie',NULL,NULL),
  ('0319','Liikenne','Ratsastusreitti','Ratsastusreitti',NULL,NULL),
  ('0320','Liikenne','Rautatieasema','Rautatieasema',NULL,NULL),
  ('0321','Liikenne','Seututie/pääkatu','Seututie/pääkatu',NULL,NULL),
  ('0322','Liikenne','Seutuverkon pyöräilyreitti','Seutuverkon pyöräilyreitti',NULL,NULL),
  ('0323','Liikenne','Suuntaisliittymä','Suuntaisliittymä',NULL,NULL),
  ('0324','Liikenne','Ulkoilu- tai virkistysreitti','Ulkoilu- tai virkistysreitti',NULL,NULL),
  ('0325','Liikenne','Valtatie/kantatie','Valtatie/kantatie',NULL,NULL),
  ('0326','Liikenne','Varattu joukkoliikenteelle','Varattu joukkoliikenteelle',NULL,NULL),
  ('0327','Liikenne','Varikko','Varikko',NULL,NULL),
  ('0328','Liikenne','Venesatama/venevalkama','Venesatama/venevalkama',NULL,NULL),
  ('0329','Liikenne','Veneväylä','Veneväylä',NULL,NULL),
  ('0330','Liikenne','Yhdysrata/sivurata/kaupunkirata','Yhdysrata/sivurata/kaupunkirata',NULL,NULL),
  ('0331','Liikenne','Yhdystie/kokoojakatu','Yhdystie/kokoojakatu',NULL,NULL),
  ('0334','Liikenne','Liityntäpysäköinti','Liityntäpysäköinti',NULL,NULL),
  ('0335','Liikenne','Muu liikenteeseen liittyvä määräys','Muu liikenteeseen liittyvä määräys',NULL,NULL),
  ('04','Kehittämisperiaatteet',NULL,'Kehittämisperiaatteet',NULL,NULL),
  ('0401','Kehittämisperiaatteet','Yhdyskuntarakenteen laajenemissuunta','Yhdyskuntarakenteen laajenemissuunta',NULL,NULL),
  ('0402','Kehittämisperiaatteet','Yhdyskuntarakenteen mahdollinen laajenemisalue','Yhdyskuntarakenteen mahdollinen laajenemisalue',NULL,NULL),
  ('0403','Kehittämisperiaatteet','Alueen eheyttämis- tai tiivistämistarve','Alueen eheyttämis- tai tiivistämistarve',NULL,NULL),
  ('0404','Kehittämisperiaatteet','Ohjeellinen tai vaihtoehtoinen tielinjaus','Ohjeellinen tai vaihtoehtoinen tielinjaus',NULL,NULL),
  ('0405','Kehittämisperiaatteet','Tieliikenteen yhteystarve','Tieliikenteen yhteystarve',NULL,NULL),
  ('0406','Kehittämisperiaatteet','Joukkoliikenteen kehittämiskäytävä tai yhteystarve','Joukkoliikenteen kehittämiskäytävä tai yhteystarve',NULL,NULL),
  ('0407','Kehittämisperiaatteet','Kevyen liikenteen yhteystarve','Kevyen liikenteen yhteystarve',NULL,NULL),
  ('0408','Kehittämisperiaatteet','Johdon, putken tai linjan yhteystarve','Johdon, putken tai linjan yhteystarve',NULL,NULL),
  ('0409','Kehittämisperiaatteet','Viheryhteystarve','Viheryhteystarve',NULL,NULL),
  ('0410','Kehittämisperiaatteet','Virkistyksen yhteystarve','Virkistyksen yhteystarve',NULL,NULL),
  ('0411','Kehittämisperiaatteet','Julkisen virkistyksen kehittämistarve','Julkisen virkistyksen kehittämistarve',NULL,NULL),
  ('0412','Kehittämisperiaatteet','Kävely-ympäristön kehittämistarve','Kävely-ympäristön kehittämistarve',NULL,NULL),
  ('0413','Kehittämisperiaatteet','Kaupunkikuvallinen kehittämistarve','Kaupunkikuvallinen kehittämistarve',NULL,NULL),
  ('0414','Kehittämisperiaatteet','Meluntorjuntatarve','Meluntorjuntatarve',NULL,NULL),
  ('0415','Kehittämisperiaatteet','Ympäristö- tai maisemavaurion korjaustarve','Ympäristö- tai maisemavaurion korjaustarve',NULL,NULL),
  ('0416','Kehittämisperiaatteet','Terveyshaitan poistamistarve','Terveyshaitan poistamistarve',NULL,NULL),
  ('0418','Kehittämisperiaatteet','Uusi tai olennaisesti muuttuva alue','Uusi tai olennaisesti muuttuva alue',NULL,NULL),
  ('0419','Kehittämisperiaatteet','Pienin toimenpitein kehitettävä alue','Pienin toimenpitein kehitettävä alue',NULL,NULL),
  ('0421','Kehittämisperiaatteet','Muu kehittämisperiaate','Muu kehittämisperiaate',NULL,NULL),
  ('05','Rajoitukset',NULL,'Rajoitukset',NULL,NULL),
  ('0501','Rajoitukset','Rakentamisrajoitus','Rakentamisrajoitus',NULL,NULL),
  ('0502','Rajoitukset','Määräaikainen rakentamisrajoitus','Määräaikainen rakentamisrajoitus',NULL,NULL),
  ('0503','Rajoitukset','Toimenpiderajoitus','Toimenpiderajoitus',NULL,NULL),
  ('0504','Rajoitukset','Rakennuksen purkamisrajoitus','Rakennuksen purkamisrajoitus',NULL,NULL),
  ('06','Alueen osan erityisominaisuudet',NULL,'Alueen osan erityisominaisuudet',NULL,NULL),
  ('0601','Alueen osan erityisominaisuudet','Erityisharkinta-alue','Erityisharkinta-alue',NULL,NULL),
  ('0602','Alueen osan erityisominaisuudet','Kehittämisalue','Kehittämisalue',NULL,NULL),
  ('0603','Alueen osan erityisominaisuudet','Vaara-alue','Vaara-alue',NULL,NULL),
  ('0604','Alueen osan erityisominaisuudet','Suojavyöhyke','Suojavyöhyke',NULL,NULL),
  ('0605','Alueen osan erityisominaisuudet','Suunnittelutarvealue','Suunnittelutarvealue',NULL,NULL),
  ('0606','Alueen osan erityisominaisuudet','Reservialue','Reservialue',NULL,NULL),
  ('0607','Alueen osan erityisominaisuudet','Muu alueen osan erityisominaisuus','Muu alueen osan erityisominaisuus',NULL,NULL),
  ('07','Ympäristöarvojen vaaliminen',NULL,'Ympäristöarvojen vaaliminen',NULL,NULL),
  ('0701','Ympäristöarvojen vaaliminen','Kulttuurihistoriallisesti arvokas alue tai kohde','Kulttuurihistoriallisesti arvokas alue tai kohde',NULL,NULL),
  ('070101','Ympäristöarvojen vaaliminen','Kulttuurihistoriallisesti arvokas alue tai kohde','Suojeltava alue tai alueen osa',NULL,NULL),
  ('070102','Ympäristöarvojen vaaliminen','Kulttuurihistoriallisesti arvokas alue tai kohde','Suojeltava rakennus',NULL,NULL),
  ('070103','Ympäristöarvojen vaaliminen','Kulttuurihistoriallisesti arvokas alue tai kohde','Suojeltava rakennelma',NULL,NULL),
  ('070104','Ympäristöarvojen vaaliminen','Kulttuurihistoriallisesti arvokas alue tai kohde','Kiinteä suojeltava kohde',NULL,NULL),
  ('070105','Ympäristöarvojen vaaliminen','Kulttuurihistoriallisesti arvokas alue tai kohde','Kiinteä muinaisjäännös','Alue tai alueen osa, jolla sijaitsee muinaismuistolailla rauhoitettu kiinteä muinaisjäännös',NULL),
  ('0702','Ympäristöarvojen vaaliminen','Luontoarvoiltaan arvokas alue tai kohde','Luontoarvoiltaan arvokas alue tai kohde',NULL,NULL),
  ('070201','Ympäristöarvojen vaaliminen','Luontoarvoiltaan arvokas alue tai kohde','Suojeltu puu',NULL,NULL),
  ('070202','Ympäristöarvojen vaaliminen','Luontoarvoiltaan arvokas alue tai kohde','Säilytettävä puu',NULL,NULL),
  ('070203','Ympäristöarvojen vaaliminen','Luontoarvoiltaan arvokas alue tai kohde','Suojeltava vesistö tai vesialue',NULL,NULL),
  ('070204','Ympäristöarvojen vaaliminen','Luontoarvoiltaan arvokas alue tai kohde','Luonnon monimuotoisuuden kannalta tärkeä alue',NULL,NULL),
  ('070205','Ympäristöarvojen vaaliminen','Luontoarvoiltaan arvokas alue tai kohde','Ekologinen yhteys',NULL,NULL),
  ('0703','Ympäristöarvojen vaaliminen','Alue, jolla ympäristö säilytetään','Alue, jolla ympäristö säilytetään',NULL,NULL),
  ('0704','Ympäristöarvojen vaaliminen','Alue, jolla on erityistä ulkoilun ohjaamistarvetta','Alue, jolla on erityistä ulkoilun ohjaamistarvetta',NULL,NULL),
  ('08','Yleismääräykset',NULL,'Yleismääräykset',NULL,NULL),
  ('0801','Yleismääräykset','Yleismääräys','Yleismääräys',NULL,NULL),
  ('0802','Yleismääräykset','Yleiskaavan käyttö rakennusluvan myöntämisen perusteena','Yleiskaavan käyttö rakennusluvan myöntämisen perusteena',NULL,NULL),
  ('09','Yhdyskuntatekninen huolto',NULL,'Yhdyskuntatekninen huolto',NULL,NULL),
  ('0901','Yhdyskuntatekninen huolto','Johto, putki tai linja','Johto, putki tai linja','Yhdyskuntatekniikkaa palveleva johto, putki tai linja, joka voi sijaita maan päällä tai alla. Tällaisia ovat esimerkiksi sähkölinjat, vesijohdot, maakaasun runkoputket ja jätevesiviemärit.',NULL),
  ('0902','Yhdyskuntatekninen huolto','Sähkölinja','Sähkölinja',NULL,NULL),
  ('0903','Yhdyskuntatekninen huolto','Kaasulinja','Kaasulinja',NULL,NULL),
  ('0904','Yhdyskuntatekninen huolto','Vesi- tai jätevesitunneli','Vesi- tai jätevesitunneli',NULL,NULL),
  ('0905','Yhdyskuntatekninen huolto','Vesijohto tai siirtoviemäri','Vesijohto tai siirtoviemäri',NULL,NULL),
  ('0906','Yhdyskuntatekninen huolto','Kaukolämpölinja','Kaukolämpölinja',NULL,NULL),
  ('0907','Yhdyskuntatekninen huolto','Kaukokylmälinja','Kaukokylmälinja',NULL,NULL),
  ('0908','Yhdyskuntatekninen huolto','Hulevesien hallinta-alue','Hulevesien hallinta-alue',NULL,NULL),
  ('0909','Yhdyskuntatekninen huolto','Hulevesien hallinnan kannalta merkittävä alue','Hulevesien hallinnan kannalta merkittävä alue',NULL,NULL),
  ('0910','Yhdyskuntatekninen huolto','Hulevesien purkuoja/-reitti','Hulevesien purkuoja/-reitti',NULL,NULL),
  ('0911','Yhdyskuntatekninen huolto','Hulevesien viivytysalue','Hulevesien viivytysalue','Hulevesien käsittelytapaa ohjaava määräys',NULL),
  ('0912','Yhdyskuntatekninen huolto','Hulevesien käsittelytapa','Hulevesien käsittelytapa',NULL,NULL),
  ('0913','Yhdyskuntatekninen huolto','Pohjavedenottamo','Pohjavedenottamo',NULL,NULL),
  ('0914','Yhdyskuntatekninen huolto','Pohjavedenottamon lähisuoja-alue','Pohjavedenottamon lähisuoja-alue',NULL,NULL),
  ('0915','Yhdyskuntatekninen huolto','Muu yhdyskuntatekniseen huoltoon liittyvä määräys','Muu yhdyskuntatekniseen huoltoon liittyvä määräys',NULL,NULL),
  ('010','Ympäristön ja terveyden suojelu',NULL,'Ympäristön ja terveyden suojelu',NULL,NULL),
  ('01001','Ympäristön ja terveyden suojelu','Pilaantunut maa-alue','Pilaantunut maa-alue',NULL,'Alue, jolla on maaperän haitta-aineita'),
  ('01002','Ympäristön ja terveyden suojelu','Tulvavaara-alue','Tulvavaara-alue','Alue, joka on tulvavaarassa','Tulvavaara voi liittyä meritulvaan tai hulevesien aiheuttamaan tulvimiseen'),
  ('01003','Ympäristön ja terveyden suojelu','Meritulvavaara-alue','Meritulvavaara-alue',NULL,NULL),
  ('01004','Ympäristön ja terveyden suojelu','Hulevesitulvavaara-alue','Hulevesitulvavaara-alue',NULL,NULL),
  ('01005','Ympäristön ja terveyden suojelu','Valuma-alue','Valuma-alue',NULL,NULL),
  ('01006','Kehittämisperiaatteet','Virkistyskohde','Virkistyskohde',NULL,NULL),
  ('01007','Ympäristön ja terveyden suojelu','Melualue','Melualue',NULL,NULL),
  ('01008','Ympäristön ja terveyden suojelu','Pohjavesialue','Pohjavesialue',NULL,NULL),
  ('01009','Ympäristön ja terveyden suojelu','Pohjaveden muodostumisalue','Pohjaveden muodostumisalue',NULL,NULL),
  ('01010','Ympäristön ja terveyden suojelu','Arvokas harjualue tai muu geologinen muodostuma','Arvokas harjualue tai muu geologinen muodostuma',NULL,NULL),
  ('01011','Ympäristön ja terveyden suojelu','Muu ympäristönsuojeluun liittyvä määräys','Muu ympäristönsuojeluun liittyvä määräys',NULL,NULL);

CREATE TABLE code_lists.master_plan_additional_information_kind(
  id SERIAL PRIMARY KEY,
  codevalue VARCHAR(6) NOT NULL UNIQUE,
  uri VARCHAR(255) NOT NULL UNIQUE,
  preflabel_fi VARCHAR NOT NULL,
  definition_fi VARCHAR,
  description_fi VARCHAR
);

CREATE TRIGGER upsert_master_plan_additional_information_kind
  BEFORE INSERT OR UPDATE ON code_lists.master_plan_additional_information_kind
  FOR EACH ROW EXECUTE PROCEDURE code_lists.code_url_trigger('http://uri.suomi.fi/codelist/rytj/RY_KaavamaaraysLaji_YK/code/');

INSERT INTO code_lists.master_plan_additional_information_kind (codevalue, preflabel_fi, definition_fi, description_fi)
VALUES
  ('01', 'Käyttötarkoituksen osuus kerrosalasta', NULL, 'Kuvaa yhden käyttötarkoituksen osuuden yhden tai usemman rakennuksen sallitusta kerrosalasta'),
  ('02', 'Käyttötarkoituskohdistus', 'Kohdistaa liittyvän kaavamääryksen koskemaan ainoastaan lisätiedon arvona annettuja käyttötarkoituksia', NULL),
  ('03', 'Kohteen geometrian osa', 'Liitetty arvo ilmaisee sen osan liittyvän kohteen geometriasta, jota kaavamääräys koskee.', 'Esim. se osa korttelin tai tontin rajaviivaa, johon rakennukset on rakennettava kiinni, tai osa yhtenä paikkatietokohteena määritellyn liikenneväylän viivaa.'),
  ('04', 'Poisluettava käyttötarkoitus', NULL, 'Annetut käyttötarkoitukset suljetaan pois kaavamääräyksen kuvaamista sallituista käyttötarkoituksista. Käytetään, mikäli on luontevampaa sulkea tiettyjä yksityiskohtaisia käyttötarkoituksia pois sallittujen joukosta kuin kuvata kaikki sallitut käyttötarkoitukset.'),
  ('05', 'Kulttuurihistoriallinen merkittävyys', 'Kohteesta muodostettu käsitys, joka perustuu kohteen kulttuurihistoriallisten arvojen ja kulttuuristen merkitysten analysointiin sekä sen suhteuttamiseen muihin vastaaviin kohteisiin', 'Kulttuurihistoriallinen merkittävyys voi olla kansainvälinen, valtakunnallinen, maakunnallinen, paikallinen tai vähäinen.'),
  ('06', 'Kulttuurihistoriallinen arvotyyppi', 'Kohteelle määritetyt kulttuurihistorialliset ominaisuudet', 'Kulttuurihistoriallisia ominaisuuksia ovat esimerkiksi rakennustaiteellinen, rakennustekninen, arkkitehtoninen ja maisemallinen.'),
  ('07', 'Kulttuurihistoriallinen tyyppi', 'Kuvaa kohteen kulttuurihistoriallista käyttötarkoitusta', NULL),
  ('08', 'Kulttuurihistoriallisen merkittävyyden kriteerit', 'Kuvaa kulttuurihistoriallisen merkittävyyden kriteerejä, joita kohde edustaa.', 'Merkittävyys voi liittyä edustavuuteen, alkuperäisyyteen, harvinaisuuteen, tyypillisyyteen tai historialliseen merkittävyyteen.'),
  ('09', 'Ympäristö- tai luontoarvon peruste', NULL, NULL),
  ('10', 'Ympäristö- tai luontoarvon merkittävyys', NULL, NULL),
  ('11', 'Muu lisätiedon laji', NULL, NULL);
