-- Grant privileges for existing objects:
-----------------------------------------------

-- Grant privileges to qgis_admin_$MUNICIPALITYCODE$
GRANT SELECT ON ALL TABLES IN SCHEMA code_lists, $SCHEMANAME$ TO qgis_admin_$MUNICIPALITYCODE$;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA $SCHEMANAME$ TO qgis_admin_$MUNICIPALITYCODE$;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA $SCHEMANAME$ TO qgis_admin_$MUNICIPALITYCODE$;

-- Grant privileges to qgis_editor_$MUNICIPALITYCODE$
GRANT SELECT ON ALL TABLES IN SCHEMA code_lists, $SCHEMANAME$ TO qgis_editor_$MUNICIPALITYCODE$;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA $SCHEMANAME$ TO qgis_editor_$MUNICIPALITYCODE$;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA $SCHEMANAME$ TO qgis_editor_$MUNICIPALITYCODE$;



-- Grant default privileges for future objects:
-----------------------------------------------

-- Grant default privileges to qgis_admin_$MUNICIPALITYCODE$
ALTER DEFAULT PRIVILEGES IN SCHEMA code_lists GRANT SELECT ON TABLES TO qgis_admin_$MUNICIPALITYCODE$;
ALTER DEFAULT PRIVILEGES IN SCHEMA $SCHEMANAME$ GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO qgis_admin_$MUNICIPALITYCODE$;
ALTER DEFAULT PRIVILEGES IN SCHEMA $SCHEMANAME$ GRANT USAGE, SELECT ON SEQUENCES TO qgis_admin_$MUNICIPALITYCODE$;

-- Grant default privileges to qgis_editor_$MUNICIPALITYCODE$
ALTER DEFAULT PRIVILEGES IN SCHEMA code_lists GRANT SELECT ON TABLES TO qgis_editor_$MUNICIPALITYCODE$;
ALTER DEFAULT PRIVILEGES IN SCHEMA $SCHEMANAME$ GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO qgis_editor_$MUNICIPALITYCODE$;
ALTER DEFAULT PRIVILEGES IN SCHEMA $SCHEMANAME$ GRANT USAGE, SELECT ON SEQUENCES TO qgis_editor_$MUNICIPALITYCODE$;
