<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Scripts\001_initialization.sql" />
    <EmbeddedResource Include="Scripts\002_insert_code_list_data.sql" />
    <EmbeddedResource Include="Scripts\003_create_public_schema_tables.sql" />
    <EmbeddedResource Include="Scripts\004_create_public_schema_functions.sql" />
    <EmbeddedResource Include="Scripts\005_create_initial_tables.sql" />
    <EmbeddedResource Include="Scripts\006_create_initial_functions.sql" />
  	<EmbeddedResource Include="Scripts\007_create_initial_triggers.sql" />
	  <EmbeddedResource Include="Scripts\008_create_code_list_triggers.sql" />
	  <EmbeddedResource Include="Scripts\009_create_public_schema_triggers.sql" />
	  <EmbeddedResource Include="Scripts\010_create_initial_indexing.sql" />
	<EmbeddedResource Include="Scripts\011_create_ryhti_tables.sql" />
	<EmbeddedResource Include="Scripts\012_alter_initial_tables.sql" />
	<EmbeddedResource Include="Scripts\013_create_ryhti_functions.sql" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="dbup-core" Version="5.0.87" />
    <PackageReference Include="dbup-postgresql" Version="5.0.40" />
    <PackageReference Include="Npgsql" Version="8.0.2" />
  </ItemGroup>

</Project>
